### ISSUE TITLE
[BUG] ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2580)

### ISSUE THREAD

**Issue by guigoruiz1** [python-telegram-bot/python-telegram-bot#3980] opened 2023-11-22 21:06 UTC
### Steps to Reproduce

1. Start a subprocess from a command
2. Terminate the subprocess from another command

See toy model demonstrating the behaviour bellow

```
import time
import os
import multiprocessing as mp
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, filters, CallbackContext

application = ApplicationBuilder().token(os.environ.get("TELEGRAM_TOKEN")).build()
            
process = None

async def abort(update: Update, context: CallbackContext):
    original_response = await context.bot.send_message( chat_id=update.effective_chat.id, text="Aborting..." )
    process.terminate()
    await original_response.edit_text("Aborted")

async def run(update: Update,context: CallbackContext):
    original_response = await context.bot.send_message(chat_id=update.effective_chat.id, text="Initializing...")
    global process
    def test():
        i=0
        while True:
            print(i)
            time.sleep(1)
            i+=1
            
    process = mp.Process(target=test)
    process.start()

application.add_handler(CommandHandler("run", run, block=False))
application.add_handler(CommandHandler("abort", abort, block=False))

application.run_polling()

```

Replacing `terminate()` by `kill()` eliminates the error but should not be a fix to the problem as it does not terminate the process gracefully.

Using the exact same toy model with `Discord.py `works flawlessly.

### Expected behaviour

Gracefully terminate subprocess and return from command

### Actual behaviour

Subprocess is not terminated and command returns timeout error

### Operating System

Linux Jupyter 4.4.302+ #64570 SMP Thu Jul 20 00:06:38 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.6
Bot API 6.9
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
```

### Relevant log output

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/anyio/streams/tls.py", line 133, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/ssl.py", line 921, in read
    v = self._sslobj.read(len)
        ^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2580)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/anyio/streams/tls.py", line 198, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1103, in receive
    await self._protocol.read_event.wait()
  File "/opt/conda/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f5b419ee710

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "/opt/conda/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/opt/conda/lib/python3.11/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_async/connection.py", line 103, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_async/http11.py", line 133, in handle_async_request
    raise exc
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_async/http11.py", line 111, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_async/http11.py", line 176, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_async/http11.py", line 212, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "/opt/conda/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 219, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/httpx/_transports/default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "/opt/conda/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jovyan/test.py", line 31, in <module>
    application.run_polling()
  File "/opt/conda/lib/python3.11/site-packages/telegram/ext/_application.py", line 779, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/ext/_application.py", line 973, in __run
    loop.run_until_complete(self.updater.stop())  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/ext/_updater.py", line 764, in stop
    await self._stop_polling()
  File "/opt/conda/lib/python3.11/site-packages/telegram/ext/_updater.py", line 789, in _stop_polling
    await self.__polling_cleanup_cb()
  File "/opt/conda/lib/python3.11/site-packages/telegram/ext/_updater.py", line 393, in _get_updates_cleanup
    await self.bot.get_updates(
  File "/opt/conda/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 565, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/_bot.py", line 519, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/_bot.py", line 3562, in get_updates
    await self._post(
  File "/opt/conda/lib/python3.11/site-packages/telegram/_bot.py", line 607, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/_bot.py", line 635, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "/opt/conda/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 278, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/telegram/request/_httpxrequest.py", line 236, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
```

### Additional Context

This is the same error as mentioned in #3570, however, increasing the `read_timeout` (or `write_timeout`) does not fix the issue.

The abort command runs completely, editing the original message at the end, but the subprocess keeps running as if `terminate()` had not been called.  The error seems to come form the `run` command.

**Comment by Bibo-Joshi** [comment] 2023-11-22 21:20
Hi. From the traceback, this does not seem to be related (directly) to the subprocess stuff, but this is rather a duplicate of #3893.

**Comment by guigoruiz1** [comment] 2023-11-22 21:28
Hi,

Using `.run_polling(read_timeout=30)` eliminates the error message but does not fix the issue. The subprocess keeps running and the application stops responding to new commands. Have you tried the example code?

**Comment by Bibo-Joshi** [comment] 2023-11-22 21:41
I see, then I had misunderstood the sentence

> increasing the read_timeout (or write_timeout) does not fix the issue.

However, the only issue the traceback shows is the issue with ptbs graceful shutdown reported in #3983 and if increasing the timeout fixes that part, then I'm inclined to guess that the multiprocessing issue is not directly related to PTB. If the setup works with running the discord library in the child process rather than the while-true loop, this also sounds to me like the while loop might be the issue.

Please try starting and stopping the multiprocess with that loop *independently* of PTB. If that works and only starting/stopping it from handler callbacks is the issue, then we'll have to look into PTB related problems :)

**Comment by guigoruiz1** [comment] 2023-11-22 21:45
I think you misunderstood what I meant with Discord.py. If using Discord.py instead of PTB, so that the bot and commands are handled by Discord.py and PTB is not included, this example works flawlessly.

**Comment by guigoruiz1** [comment] 2023-11-22 21:49
For reference, this would be a Discord.py version of the example:
```

@self.hybrid_command(
            name="run", description="Run full YugiQuery workflow", with_app_command=True
        )
        @commands.is_owner()
        @commands.cooldown(1, 12 * 60 * 60, commands.BucketType.user)
        async def run(ctx):
            original_response = await ctx.send(
                content="Initializing...", ephemeral=True, delete_after=60
            )
            global process
            def test():
                i=0
                while True:
                    print(i)
                    time.sleep(1)
                    i+=1
                    
            process = mp.Process(target=test)
            process.start()
            
        @self.hybrid_command(
            name="abort",
            description="Abort running YugiQuery workflow",
            with_app_command=True,
        )
        @commands.is_owner()
        async def abort(ctx):
            original_response = await ctx.send(
                content="Aborting...", ephemeral=True, delete_after=60
            )
            process.abort()
            await original_response.edit(content="Aborted")
```

**Comment by Bibo-Joshi** [comment] 2023-11-23 18:22
> I think you misunderstood what I meant with Discord.py. If using Discord.py instead of PTB, so that the bot and commands are handled by Discord.py and PTB is not included, this example works flawlessly. The only difference from a code that works to a code that doesn't is using PTB as the command handler.

okay, thanks for the clarification. I tried to reproduce the issue locally. I had to move the `test` function outside of the `run` callback due to some issue with mp on windows. After that, your example worked for me without any problem. Do you have a windows machine at hand to double check on your end? I can try to check on linux in a few days.
Just to clarify (I'm not very familiar with jupyter): Is "Jupyter Linux" a standalone OS or are you running the example within jupyter notebooks? I'm asking b/c we're aware that PTB is not directly usable within jupyter notebooks (see #3251).

**Comment by guigoruiz1** [comment] 2023-11-23 20:07
I don't have a windows machine to try, but I tried on my mac and got a different error. I also had to move the test function outside, but apart from that I always receive the following error:


```
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 640, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 345, in polling_action_cb
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 334, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 565, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 519, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 3562, in get_updates
    await self._post(
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 607, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 635, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 327, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 640, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 345, in polling_action_cb
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 334, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 565, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 519, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 3562, in get_updates
    await self._post(
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 607, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 635, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 327, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 640, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 345, in polling_action_cb
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 334, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 565, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 519, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 3562, in get_updates
    await self._post(
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 607, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 635, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 327, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 640, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 345, in polling_action_cb
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 334, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 565, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 519, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 3562, in get_updates
    await self._post(
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 607, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 635, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 327, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 640, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 345, in polling_action_cb
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_updater.py", line 334, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 565, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 519, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 3562, in get_updates
    await self._post(
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 607, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/_bot.py", line 635, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 327, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
```

On Linux, being the test function inside or outside the handler, it does not work. Did it terminate the process properly and continue listening for commands when you tried?

About Jupyter, it is a docker container running jupyterlab. I run the code in the terminal, not notebooks.

**Comment by Bibo-Joshi** [comment] 2023-11-23 21:00
> I always receive the following error:

This is entirely unrelated. Pleas just make sure that only one process at a time is fetching updates from telegram, as indicated by the error message.

> Did it terminate the process properly and continue listening for commands when you tried?

Yes, I'm able to execute `/run` and `/abort` several times & then gracefully shutdown PTB via CTRL+C

>  I run the code in the terminal, not notebooks.

okay.

---

I'll try to run on linux, then, when I have the chance

**Comment by guigoruiz1** [comment] 2023-11-23 21:05
> This is entirely unrelated. Pleas just make sure that only one process at a time is fetching updates from telegram, as indicated by the error message.

I am trying to figure out what is the problem since there is only one process running.

> Yes, I'm able to execute /run and /abort several times & then gracefully shutdown PTB via CTRL+C

I am able to run the commands, but despite receiving "Aborted" on telegram, the subprocess keeps running. I still see the counter going up in the terminal despite how many times I use `/abort`. I can use`/run` again and then I have two counters in the terminal, and `/abort` won't stop neither of them.

**Comment by guigoruiz1** [comment] 2023-11-24 18:31
I have been able to run a modified example on Mac which behaved as expected, however, I can confirm that the exact same example does not work on my Linux machine. Apparently, it is a Linux-specific bug. Here is the code:

```
import time
import os
import multiprocessing as mp
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, CallbackContext
import asyncio

# Global variable to store the process created by the bot
process_instance = None

# Define the create_process command
async def create_process(update: Update, context: CallbackContext):
    global process_instance

    # Check if a process is already running
    if process_instance and process_instance.is_alive():
        await update.message.reply_text('A process is already running. Use /terminate_process to stop it.')
    else:
        # Start a new process
        original_response = await context.bot.send_message(chat_id=update.message.chat_id, text="Initializing...")
        process_instance = mp.Process(target=process_loop)
        process_instance.start()
        await original_response.edit_text('Process created.')
        def await_result():
            while process_instance.is_alive():
                time.sleep(1)
                print("Process is running!")
        
        # await await_result()      
        # await context.bot.send_message(chat_id=update.message.chat_id, text="Process completed!")


# Define the terminate_process command
async def terminate_process(update: Update, context: CallbackContext):
    global process_instance

    # Check if a process is running
    if process_instance and process_instance.is_alive():
        original_response = await context.bot.send_message(chat_id=update.message.chat_id, text="Terminating...")
        # Terminate the process
        process_instance.terminate()
        process_instance.join()
        await original_response.edit_text("Process terminated") #update.message.reply_text('Process terminated.')
    else:
        await update.message.reply_text('No process is currently running.')

# Define the function to be executed by the process
def process_loop():
    # Replace this with the actual logic of your process
    i = 0
    while i<600:
        i+=1
        time.sleep(1)
        print(f"Process is running {i}")

    

# Set up the bot and its commands
def main() -> None:
    # updater = Updater("5625441815:AAFZQ9Gf83Qm-srrnk-AsVZEmu-_AJYlebQ")
    app = ApplicationBuilder().token("TOKEN").concurrent_updates(True).build()

    app.add_handler(CommandHandler("create_process", create_process, block=False))
    app.add_handler(CommandHandler("terminate_process", terminate_process, block=False))

    app.run_polling()

if __name__ == '__main__':
    main()
```

I do have another problem still. I would like to be able to terminate the process from the `terminate_process` command even if the `create_process` command is still running. Essentially, I want the `create_process` to return then the process is complete. I have tried using `block=False` and `concurrent_updates(True)` but, if I uncomment the loop in `await await_result()` the `terminate_process` is never called as `create_process` blocks the execution. Is there a way to make it work? I thought the `block` argument was specifically for that.

**Comment by Bibo-Joshi** [comment] 2023-11-26 15:10
Hi. I was able to test on linux and found the issue: https://docs.python-telegram-bot.org/en/stable/telegram.ext.application.html#telegram.ext.Application.run_polling.params.stop_signals
On Linux, the SIGTERM emitted by `Process.terminate` seems to be catched by this signal handler. Setting `stop_signals=None` fixes the issue for me.

> Is there a way to make it work? I thought the block argument was specifically for that.

The `time.sleep` within `await_result` is blocking in the asyncio.sense. PTBs concurrency machinsems only over asyncio-friendly concurrency. Using `asyncio.sleep` instead is one option, but please also have a look at the [JobQueue](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions---JobQueue).

**Comment by guigoruiz1** [comment] 2023-11-26 16:23
Hi, thanks a lot. Using `stop_signals=None` worked for me too. But using `asyncio.sleep` instead of `time.sleep` still blocked the execution. jobqueue seems like an option, but I would like to understand why the `await_result` function won't work.

Here it is as I'm currently using:
```
async def await_result():
            while process_instance.is_alive():
                asyncio.sleep(1)
                print("Process is running!")
```

**Comment by Bibo-Joshi** [comment] 2023-11-26 16:33
`asyncio.sleep` needs to be awaited. But this is going beyond the scope of this issue tracker. I'll close this issue as the problem has beend found.

**Closed by Bibo-Joshi** 2023-11-26 16:33 UTC
Labels: bug :bug:
