### ISSUE TITLE
Bot raises NetworkError on first update after a while of being unused.

### ISSUE THREAD

**Issue by ruvolof** [python-telegram-bot/python-telegram-bot#711] opened 2017-07-07 11:28 UTC
I have seen similar issues, but those issues are now marked as closed and are supposedly resolved. 

### Steps to reproduce
1. Create a bot and leave it running without sending any message for a while (20 minutes usually are enough).

2. Send a message to it.

I have added a minimal code to reproduce the bug in the second message of this thread.

### Expected behaviour
Bot should reply.

### Actual behaviour
Bot raise a NetworkError. After this, it starts working again as it is supposed to be.

### Configuration
**Operating System:**
Ubuntu 17.04

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 6.1.0
urllib3 1.21.1
certifi 2017.04.17
future 0.16.0
Python 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
```

### Logs
```
ERROR:root:cerca_from_forward
Traceback (most recent call last):
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 174, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gnome-helper.py", line 89, in cerca_from_forward
    cerca(bot, update, custom_w=custom_w)
  File "gnome-helper.py", line 79, in cerca
    bot.send_message(update.message.chat_id, good_words, parse_mode='Markdown')
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/bot.py", line 52, in decorator
    result = func(self, *args, **kwargs)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/bot.py", line 64, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/bot.py", line 156, in _message_wrapper
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 252, in post
    **urlopen_kwargs)
  File "/home/francesco-ubn/.local/lib/python3.5/site-packages/telegram/utils/request.py", line 180, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

### Additional information
The error is raised as soon as the message is sent, this means that the getUpdates fetches the update properly. It's the bot.sendMessage method inside my callback that raise the error. This happens only if the bot does not receive any message for a while. If I keep sending messages to it, it works flawlessly.

**Comment by ruvolof** [comment] 2017-07-07 17:47
Here is a super simple bot code which is affected by the above bug.

```
from telegram.ext import Updater, MessageHandler
from telegram.ext.filters import Filters
import logging

def echo(bot, update):
    try:
        bot.send_message(update.message.chat_id, update.message.text)
    except Exception as e:
        logging.exception('echo')

updater = Updater(token='196892925:AAG_WqOpa8N0caQYUj0IwoX8oo2w-E9NUcI')
dispatcher = updater.dispatcher
echo_handler = MessageHandler(Filters.text, echo)
dispatcher.add_handler(echo_handler)
updater.start_polling()
updater.idle()
```

**Comment by evgfilim1** [comment] 2017-07-20 05:19
This can be easily reproduced, I think, because sometimes I get the same error with the same conditions, so +1

**Comment by tsnoam** [comment] 2017-07-29 13:42
@ruvolof 
I tried recreating the issue and failed. I think it is related to exact timing.
Do you see retry attempts?

**Comment by MaksimSergienko** [comment] 2017-08-06 12:58
I have this error while posting a file
`            result = bot.send_audio(chat_id=chat_id,
                                    audio=open(fresh_audiofile['file_path'], 'rb'),
                                    title=fresh_audiofile['title'],
                                    caption=fresh_audiofile['artist'])`

and have error
ERROR:JobQueue:An uncaught error was raised while executing job callback_minute
Traceback (most recent call last):
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 636, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\utils\request.py", line 174, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 70, in request
    **urlopen_kw)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 390, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 636, in write
    return self._sslobj.write(data)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\jobqueue.py", line 289, in tick
    job.run(self.bot)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\jobqueue.py", line 422, in run
    self.callback(bot, self)
  File "C:\Users\Максим\PycharmProjects\tgmb\media_library_bot.py", line 20, in callback_minute
    caption=fresh_audiofile['artist'])
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\bot.py", line 69, in decorator
    return self._message_wrapper(url, data, *args, **kwargs)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\bot.py", line 175, in _message_wrapper
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\utils\request.py", line 248, in post
    'POST', url, body=data.to_form(), headers=data.headers, **urlopen_kwargs)
  File "C:\Users\Максим\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\utils\request.py", line 180, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out',))

**Comment by ruvolof** [comment] 2017-08-06 14:38
@tsnoam I'm now out of town and won't be back for a while. If you want, once I'm back I can get in touch with you and easily setup a Pi to reverse ssh to any destination of your choice. This way, you can directly test and debug the bot on a machine where this issue is very easy to reprouce (it happens every time, 100%).

**Comment by tsnoam** [comment] 2017-08-08 20:19
@ruvolof 
You are very kind, looking at such problems with actual hands on will be of great help.
Please contact me at telegram.me/tsnoam so I can send you my SSH public key.

**Comment by aermetici** [comment] 2017-08-31 19:52
I could also reproduce with v7.0.1

The issue is not present when installing from source

**Comment by tsnoam** [comment] 2017-10-11 20:46
@ruvolof 
are you available for testing as suggested? you can contact me on telegram as @tsnoam

@MaksimSergienko you're probably sending a large file and need to extend the timeout. Check the documentation and if you're not already there, you're welcome to join our community for usage questions: https://t.me/pythontelegrambotgroup

**Comment by ruvolof** [comment] 2017-10-14 17:04
I'm no longer able to reproduce the issue with the latest version of python-telegram-bot. This is the current configuration:

```
python-telegram-bot 8.0
certifi 2017.07.27.1
future 0.16.0
Python 3.5.3 (default, Sep 14 2017, 22:58:41)  [GCC 6.3.0 20170406]
```

**Comment by Detrous** [comment] 2017-10-24 03:20
Same problem when edit_message_reply_markup

**Comment by Eldinnie** [comment] 2017-10-26 18:34
Good! Can we close?

**Comment by ysoftware** [comment] 2017-12-06 22:13
I still get this error.
bot 8.1.1
future 0.16.0
certifi 2017.11.05
Python 3.6.3

**Comment by korcky** [comment] 2017-12-12 11:12
@ysoftware mb you should use python-telegram-bot instead of bot

**Comment by tsnoam** [comment] 2018-02-15 12:08
@ruvolof the reporter of this issue says that it is fixed in the new version - closing.

@ysoftware if you're still having problems make sure you upgrade to the latest version of ptb and take a look at the wiki page I've just uploaded regarding network errors https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors
it's a new page and every comment is appreciated.

**Closed by tsnoam** 2018-02-15 12:08 UTC

**Comment by takasurazeem** [comment] 2020-08-20 05:50
I am facing this same issue in 12.8
