### ISSUE TITLE
parse_entity use an odd offset

### ISSUE THREAD

**Issue by Marocco2** [python-telegram-bot/python-telegram-bot#1057] opened 2018-03-26 10:57 UTC
### Steps to reproduce

I use this definition:
![image](https://user-images.githubusercontent.com/3944248/37902235-107dd466-30f4-11e8-9968-85bd7341d205.png)

### Expected behaviour
It should parse URL link in this message 
`Pirelli: strategia vincente per Vettel in Australia https://www.formulapassion.it/motorsport/formula-1/pirelli-strategia-vincente-per-vettel-in-australia-375234.html`

### Actual behaviour
Actually it doesn't parse (it works fine in a very similar function). See attached logs

### Configuration
**Operating System:** Windows 10

**Version of Python, python-telegram-bot & dependencies:** Python 3.5
![image](https://user-images.githubusercontent.com/3944248/37902439-b4610fa8-30f4-11e8-9bc0-8e10a57da9c8.png)

### Logs
![image](https://user-images.githubusercontent.com/3944248/37902510-ee4586b8-30f4-11e8-843d-57e974f865ca.png)

https://gist.github.com/Marocco2/105f80f64fe0651c1b7e825c1956ff4e

**Comment by Eldinnie** [comment] 2018-03-26 11:13
Hi,
It seems to me the error is caused by trying to send a message with bad markdown, rather that the parsing of the entity:
https://gist.github.com/Marocco2/105f80f64fe0651c1b7e825c1956ff4e#file-commenti-py-L306
try sending with html. It usualy fix these kind of troubles, created by markdown within users usernames or other text.

**Comment by Marocco2** [comment] 2018-03-26 11:34
Tried with HTML, same log error

**Comment by Eldinnie** [comment] 2018-03-26 12:03
With the same offset number?

**Comment by Marocco2** [comment] 2018-03-26 12:15
Yes, 73 . Everytime, also with other messages that I send

**Comment by Eldinnie** [comment] 2018-03-26 12:17
Then you probably did not switch over to html insterad of markdown.

Anyway this is not an issue with the library's code, but a usage question. Feel free to ask it in our [telegram group](https://t.me/pythontelegrambotgroup). Or (if you can't reach our group) our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot)

I'm closing the issue.

**Closed by Eldinnie** 2018-03-26 12:17 UTC

**Comment by Marocco2** [comment] 2018-03-26 12:35
But why it's calling a parse issue instead a markdown issue?

**Comment by Marocco2** [comment] 2018-03-26 12:35
And I did HTML changes
