### ISSUE TITLE
[FEATURE] Filters.command only filters "/" commands, and it's not based on a list of commands

### ISSUE THREAD

**Issue by Geek-MD** [python-telegram-bot/python-telegram-bot#2992] opened 2022-05-04 03:10 UTC
### Steps to Reproduce

1. dispatcher.add_handler(MessageHandler(~Filters.command, not_command))

### Expected behaviour

When you type a command that is not defined by CommandHandler, Filters.command shouldn't recognize it as a valid command.

### Actual behaviour

When I type a command like "/asdf" that it's not defined with CommandHandler, Filters.command recognizes it as a command, instead of filtering it compared with a commands list.

### Operating System

macOS Monterey 12.3.1

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11
Bot API 5.7
certifi 2021.10.08
Python 3.9.10 (main, Jan 15 2022, 11:40:53)  [Clang 13.0.0 (clang-1300.0.29.3)]
```

**Comment by Bibo-Joshi** [comment] 2022-05-04 06:19
Hi. `Filters.command` accepting *any* command is [well documented](https://python-telegram-bot.readthedocs.io/en/stable/telegram.ext.filters.html#telegram.ext.filters.Filters.command) behavior and hence not a bug.

I don't see a reason why `Filters.command` should accept a list of valid commands. For that use case, we already have `CommandHandler` in place (which btw can also accept filters). Moreover I'd argue that catching commands *not* handled by a `CommandHandler` is the main use case of `Filters.command`, e.g. something like

```python
add_handler(Commandhandler(['some', 'commands'], handle_commands))
add_handler(MessageHandler(
    Filters.command,
    lambda u, c: u.message.reply_text("invalid command - please try a different one")
))
```

Apart from that, handlers are independent from one another and also filters are independent from handlers. so `Filters.command` can't possibly know which commands where registered in a `CommandHandler`.

**Comment by Bibo-Joshi** [comment] 2022-05-07 18:29
I went ahead closed this feature request for the reasons mentioned above - if someone disagrees, feel free to comment.

**Closed** 2022-05-07 18:28 UTC
Labels: enhancement
