### ISSUE TITLE
Invalid server response in request.py

### ISSUE THREAD

**Issue by springjools** [python-telegram-bot/python-telegram-bot#196] opened 2016-03-10 17:15 UTC
I made a bot with my own token, and substituted that for the token in the examples/timerbot.py. Yestertday it worked fine, but today I get this:
![telegrambot](https://cloud.githubusercontent.com/assets/5911982/13677812/5279cce0-e6f4-11e5-83ec-60cf242464b2.png)

I can't get it working even if I try to catch the exception in the startpolling() function in main().

Maybe it's a temporary network problem, but I added a ping at the start and that works. Sometimes I also get bad gateway instead of invalid server response.

**Comment by leandrotoledo** [comment] 2016-03-11 20:03
Would you please post the piece of code where you are trying to handle this exception so we can try to reproduce?

Thanks.

**Comment by springjools** [comment] 2016-03-12 14:50
I have already modified the code a bit, but it should be very similar to this:

http://pastebin.com/fkkMJbJp

BTW, I think it was caused by a network problem, since it started working the next day again. And it was reproducible with several example bots, I also tried the cli-bot and the exhobot. And I also tried revoking and renewing my token, it was not that.

Even if it was a network problem, I think the issue still is that the exception should be caught.

**Comment by tsnoam** [comment] 2016-03-13 18:38
looks like `bot.setWebhook()` (clear webhook) in the begiinning of _start_polling() failed due to a telegram server error.

in general, i don't think it should be part of out responsibility to retry on telegram server errors, however, the bootstraping of the Updater is a special case.

i will fix the code as following:
start_polling() & start_webhook() will receive a parameter: `bootstrap_retries`. (allowing no retry, indefinitely or up to X retries) 
this will allow retries only on the bootstrapping phase.

**Comment by jh0ker** [comment] 2016-03-17 12:06
#202 has been merged, so I will close this issue

**Closed by jh0ker** 2016-03-17 12:06 UTC
Labels: bug
