### ISSUE TITLE
Inlinebot example doesn't work

### ISSUE THREAD

**Issue by aarondiazr** [python-telegram-bot/python-telegram-bot#441] opened 2016-10-16 05:14 UTC
Hi!!

When I try to run inlinebot example from this repo, takes too long time to execute, and log return:

```
2016-10-15 01:39:06,515 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=<object object at 0x7fccae3f30d0>)",)': /bot:TOKEN/sendMessage

2016-10-15 04:19:47,319 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15.0)",)': /bot:TOKEN/getUpdates
```

My bot is /setinline option activated. Anyone knows how to fix?

Thanx!

**Comment by bomjacob** [comment] 2016-10-16 11:03
I am unable to reproduce...
Does the simple test commands /start and /help work in the example, or is the bot bot unresponsive?
It seems like it's probably an issue with your bot's internet connection, could you perhaps try on another connection?

**Comment by aarondiazr** [comment] 2016-10-16 12:54
When test /start and /help command works fine, the program return the response, but inline query still not working.

**Comment by bomjacob** [comment] 2016-10-16 12:56
Could you try posting the full output of a debug log? (change line 29 to `level=logging.DEBUG)`)

**Comment by aarondiazr** [comment] 2016-10-16 13:02
ok

> 2016-10-16 07:58:40,644 - JobQueue - DEBUG - Auto-starting JobQueue
2016-10-16 07:58:40,645 - JobQueue - DEBUG - JobQueue thread started
2016-10-16 07:58:40,645 - telegram.ext.dispatcher - DEBUG - Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x7ff5ecf2df90>
2016-10-16 07:58:40,648 - telegram.ext.updater - DEBUG - dispatcher - started
2016-10-16 07:58:40,649 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2016-10-16 07:58:40,649 - telegram.ext.updater - DEBUG - updater - started
2016-10-16 07:58:40,649 - telegram.ext.updater - DEBUG - Updater thread started
2016-10-16 07:58:40,650 - telegram.bot - DEBUG - Entering: setWebhook
2016-10-16 07:58:41,605 - telegram.bot - DEBUG - True
2016-10-16 07:58:41,605 - telegram.bot - DEBUG - Exiting: setWebhook
2016-10-16 07:58:41,605 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 07:58:51,812 - telegram.bot - DEBUG - No new updates found.
2016-10-16 07:58:51,812 - telegram.bot - DEBUG - []
2016-10-16 07:58:51,812 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 07:58:51,812 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 07:59:02,021 - telegram.bot - DEBUG - No new updates found.
2016-10-16 07:59:02,021 - telegram.bot - DEBUG - []
2016-10-16 07:59:02,022 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 07:59:02,022 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 07:59:11,649 - telegram.bot - DEBUG - Getting updates: [343053971]
2016-10-16 07:59:11,649 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x7ff5ecf55210>]
2016-10-16 07:59:11,649 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 07:59:11,650 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 07:59:11,658 - telegram.ext.dispatcher - DEBUG - Processing Update: {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [{'length': 6, 'type': u'bot_command', 'offset': 0}], 'text': u'/start', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': '', 'first_name': u'is', 'last_name': '', 'type': '', 'id': 8680711}, 'supergroup_chat_created': False, 'chat': {'username': '', 'first_name': u'is', 'last_name': '', 'title': '', 'type': u'private', 'id': 8680711}, 'photo': [], 'date': 1476622751, 'group_chat_created': False, 'caption': '', 'message_id': 287, 'new_chat_title': ''}, 'update_id': 343053971}
2016-10-16 07:59:11,659 - telegram.bot - DEBUG - Entering: sendMessage
2016-10-16 07:59:12,668 - telegram.bot - DEBUG - {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [], 'text': u'Hi!', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': u'Mi_primer_Bot', 'first_name': u'Mi primer bot \U0001f423', 'last_name': '', 'type': '', 'id': 299989061}, 'supergroup_chat_created': False, 'chat': {'username': '', 'first_name': u'is', 'last_name': '', 'title': '', 'type': u'private', 'id': 8680711}, 'photo': [], 'date': 1476622752, 'group_chat_created': False, 'caption': '', 'message_id': 288, 'new_chat_title': ''}
2016-10-16 07:59:12,668 - telegram.bot - DEBUG - Exiting: sendMessage
2016-10-16 07:59:15,057 - telegram.bot - DEBUG - Getting updates: [343053972]
2016-10-16 07:59:15,058 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x7ff5ecf55690>]
2016-10-16 07:59:15,058 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 07:59:15,058 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 07:59:15,085 - telegram.ext.dispatcher - DEBUG - Processing Update: {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [{'length': 5, 'type': u'bot_command', 'offset': 0}], 'text': u'/help', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': '', 'first_name': u'is', 'last_name': '', 'type': '', 'id': 8680711}, 'supergroup_chat_created': False, 'chat': {'username': '', 'first_name': u'is', 'last_name': '', 'title': '', 'type': u'private', 'id': 8680711}, 'photo': [], 'date': 1476622754, 'group_chat_created': False, 'caption': '', 'message_id': 289, 'new_chat_title': ''}, 'update_id': 343053972}
2016-10-16 07:59:15,086 - telegram.bot - DEBUG - Entering: sendMessage
2016-10-16 07:59:15,413 - telegram.bot - DEBUG - {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [], 'text': u'Help!', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': u'Mi_primer_Bot', 'first_name': u'Mi primer bot \U0001f423', 'last_name': '', 'type': '', 'id': 299989061}, 'supergroup_chat_created': False, 'chat': {'username': '', 'first_name': u'is', 'last_name': '', 'title': '', 'type': u'private', 'id': 8680711}, 'photo': [], 'date': 1476622755, 'group_chat_created': False, 'caption': '', 'message_id': 290, 'new_chat_title': ''}
2016-10-16 07:59:15,413 - telegram.bot - DEBUG - Exiting: sendMessage
2016-10-16 07:59:25,267 - telegram.bot - DEBUG - No new updates found.
2016-10-16 07:59:25,267 - telegram.bot - DEBUG - []
2016-10-16 07:59:25,267 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 07:59:25,267 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 07:59:35,475 - telegram.bot - DEBUG - No new updates found.
2016-10-16 07:59:35,475 - telegram.bot - DEBUG - []
2016-10-16 07:59:35,475 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 07:59:35,475 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 07:59:45,683 - telegram.bot - DEBUG - No new updates found.
2016-10-16 07:59:45,683 - telegram.bot - DEBUG - []
2016-10-16 07:59:45,683 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 07:59:45,683 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 07:59:55,893 - telegram.bot - DEBUG - No new updates found.
2016-10-16 07:59:55,893 - telegram.bot - DEBUG - []
2016-10-16 07:59:55,893 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 07:59:55,893 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:00:06,102 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:00:06,102 - telegram.bot - DEBUG - []
2016-10-16 08:00:06,102 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:00:06,102 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:00:16,309 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:00:16,309 - telegram.bot - DEBUG - []
2016-10-16 08:00:16,309 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:00:16,310 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:00:26,519 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:00:26,519 - telegram.bot - DEBUG - []
2016-10-16 08:00:26,519 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:00:26,520 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:00:36,734 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:00:36,734 - telegram.bot - DEBUG - []
2016-10-16 08:00:36,734 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:00:36,734 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:00:46,943 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:00:46,943 - telegram.bot - DEBUG - []
2016-10-16 08:00:46,943 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:00:46,943 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:00:57,153 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:00:57,154 - telegram.bot - DEBUG - []
2016-10-16 08:00:57,154 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:00:57,154 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:00:58,946 - telegram.bot - DEBUG - Getting updates: [343053973]
2016-10-16 08:00:58,947 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x7ff5ecf55cd0>]
2016-10-16 08:00:58,947 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:00:58,947 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:00:58,959 - telegram.ext.dispatcher - DEBUG - Processing Update: {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [{'length': 14, 'type': u'mention', 'offset': 0}], 'text': u'@Mi_primer_Bot Caps hola', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': '', 'first_name': u'is', 'last_name': '', 'type': '', 'id': 8680711}, 'supergroup_chat_created': False, 'chat': {'username': '', 'first_name': u'is', 'last_name': '', 'title': '', 'type': u'private', 'id': 8680711}, 'photo': [], 'date': 1476622858, 'group_chat_created': False, 'caption': '', 'message_id': 291, 'new_chat_title': ''}, 'update_id': 343053973}
2016-10-16 08:01:09,186 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:01:09,187 - telegram.bot - DEBUG - []
2016-10-16 08:01:09,187 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:01:09,187 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:01:19,394 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:01:19,394 - telegram.bot - DEBUG - []
2016-10-16 08:01:19,394 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:01:19,395 - telegram.bot - DEBUG - Entering: getUpdates
2016-10-16 08:01:29,601 - telegram.bot - DEBUG - No new updates found.
2016-10-16 08:01:29,601 - telegram.bot - DEBUG - []
2016-10-16 08:01:29,602 - telegram.bot - DEBUG - Exiting: getUpdates
2016-10-16 08:01:29,602 - telegram.bot - DEBUG - Entering: getUpdates

**Comment by aarondiazr** [comment] 2016-10-16 15:05
It seems nothing happen when using inline query...I put @miBot in text input message, but doesn't work...and I tried with other python project (pyTelegramBotAPI) but still not work.....Maybe can be a changes in Telegram API or something like that?

**Comment by bomjacob** [comment] 2016-10-16 15:07
This leaves me to think that you have not configured the bot correctly with BotFather... please try creating a new one (remember to change the token in the code) and enabling inline on the new bot. And if you can please attach a screenshot of that conversation with botfather.

**Comment by aarondiazr** [comment] 2016-10-16 15:29
ok, I made a new bot, but still happen the same with inline query
![image](https://cloud.githubusercontent.com/assets/4606280/19418470/1c796310-938a-11e6-9f5c-bed4589fae5a.png)

attach of my test (gif animation)

![output](https://cloud.githubusercontent.com/assets/4606280/19418522/d58a4fae-938a-11e6-8982-3a4f8231bf6a.gif)

**Comment by bomjacob** [comment] 2016-10-16 15:33
Did you send a message after sending "`@myprimerbot`" to botfather? It's quite important that you do. the /setinline command is not finished till botfather replies with "Success! Inline settings updated. /help"!

**Comment by aarondiazr** [comment] 2016-10-16 15:47
ohhh you're right, was my fault, I did not know I had to send @mybot after the telegram response...

> This will enable inline queries for your bot. https://core.telegram.org/bots/inline. Use /setnoinline to disable.
> To enable inline mode, **please send me** the placeholder message for queries to your bot. People will see this placeholder whenever they type @myprimer_bot in the message field – in any chat. Tell them what they can get from your bot (e.g., Search GIFs...).

I assumed that only with the first command is activated inline mode, but I need to send again the username of my bot to enable successfully. Now everything works fine...Thanx!!!!

**Comment by bomjacob** [comment] 2016-10-16 15:48
Good to hear :)
I will close this issue then.

**Closed by bomjacob** 2016-10-16 15:48 UTC
