### ISSUE TITLE
[BUG] Running daily Job from JobQueue late because of repeating job scheduling

### ISSUE THREAD

**Issue by matveyplevako** [python-telegram-bot/python-telegram-bot#1903] opened 2020-04-19 11:11 UTC
### Steps to reproduce
1. Create daily job
2. Create repeating job, that on average runs longer that its interval.

### Expected behaviour
Daily job runs at specified time.

### Actual behaviour
Daily job runs with increasing delays.

PQ - PriorityQueue
Example:
1. Create daily job (1) to be executed at time t=60
PQ state ((60, (1)))
2. Create repeating job (2) to be executed every 10 seconds and it will run for 40 seconds
PQ state ((0, (2)), (60, (1)))
3. At t=0 (2) starts  and runs until t=40
PQ state ((60, (1)))
4. Scheduler enqueues new job(3) with previous_t=0 and interval=10, so it has next_t=10
PQ state ((10, (3)), (60, (1)))
5. At t=40 priority queue picks (3) with t=10 and runs it for 40 seconds
PQ state ((60, (1)))
6. Scheduler enqueues new job(4) with previous_t=10 and interval=10, so it has next_t=20
PQ state ((20, (4)), (60, (1)))
7. At t=80 priority queue picks (4) with t=20 and runs it for 40 seconds
PQ state ((60, (1)))
8. Scheduler enqueues new job(5) with previous_t=20 and interval=10, so it has next_t=30
PQ state ((30, (5)), (60, (1)))

And this will continue until next_t will be greater than (1) job time.

### Example 
```
def hand(context):
    global i
    sleep(3)
    logging.info(f"Running {i}th time")
    i += 1
def important(context):
    logging.info("important Hello world!")


def main():
    TOKEN = 'token'
    updater = Updater(token=TOKEN, use_context=True)

    updater.dispatcher.add_handler(CommandHandler("start", hand))

    updater.job_queue.run_repeating(hand, 1)
    updater.job_queue.run_once(important, 6)

    updater.start_polling()


if __name__ == '__main__':
    main()
```
### Logs
We should see important Hello world at 11th second, but we see it on 24th. 

```
DEBUG      2020-04-19 14:05:05,567 JobQueue                       _put                                 95  : Putting job hand with t=1587294306.567979
DEBUG      2020-04-19 14:05:05,568 JobQueue                       _put                                 95  : Putting job important with t=1587294311.568107
DEBUG      2020-04-19 14:05:05,723 JobQueue                       start                                293 : JobQueue thread started
DEBUG      2020-04-19 14:05:06,568 JobQueue                       tick                                 240 : Ticking jobs with t=1587294306.568142
DEBUG      2020-04-19 14:05:06,568 JobQueue                       tick                                 248 : Peeked at hand with t=1587294306.567979
DEBUG      2020-04-19 14:05:06,568 JobQueue                       tick                                 269 : Running job hand
INFO       2020-04-19 14:05:09,573 root                           hand                                 24  : Running 0th time
DEBUG      2020-04-19 14:05:09,574 JobQueue                       _put                                 95  : Putting job hand with t=1587294307.567979
DEBUG      2020-04-19 14:05:09,574 JobQueue                       tick                                 248 : Peeked at hand with t=1587294307.567979
DEBUG      2020-04-19 14:05:09,574 JobQueue                       tick                                 256 : Next task isn't due yet. Finished!
DEBUG      2020-04-19 14:05:09,574 JobQueue                       tick                                 240 : Ticking jobs with t=1587294309.574547
DEBUG      2020-04-19 14:05:09,574 JobQueue                       tick                                 248 : Peeked at hand with t=1587294307.567979
DEBUG      2020-04-19 14:05:09,574 JobQueue                       tick                                 269 : Running job hand
INFO       2020-04-19 14:05:12,576 root                           hand                                 24  : Running 1th time
DEBUG      2020-04-19 14:05:12,576 JobQueue                       _put                                 95  : Putting job hand with t=1587294308.567979
DEBUG      2020-04-19 14:05:12,577 JobQueue                       tick                                 248 : Peeked at hand with t=1587294308.567979
DEBUG      2020-04-19 14:05:12,577 JobQueue                       tick                                 269 : Running job hand
INFO       2020-04-19 14:05:15,578 root                           hand                                 24  : Running 2th time
DEBUG      2020-04-19 14:05:15,578 JobQueue                       _put                                 95  : Putting job hand with t=1587294309.567979
DEBUG      2020-04-19 14:05:15,579 JobQueue                       tick                                 248 : Peeked at hand with t=1587294309.567979
DEBUG      2020-04-19 14:05:15,579 JobQueue                       tick                                 269 : Running job hand
INFO       2020-04-19 14:05:18,582 root                           hand                                 24  : Running 3th time
DEBUG      2020-04-19 14:05:18,583 JobQueue                       _put                                 95  : Putting job hand with t=1587294310.567979
DEBUG      2020-04-19 14:05:18,583 JobQueue                       tick                                 248 : Peeked at hand with t=1587294310.567979
DEBUG      2020-04-19 14:05:18,583 JobQueue                       tick                                 256 : Next task isn't due yet. Finished!
DEBUG      2020-04-19 14:05:18,583 JobQueue                       tick                                 240 : Ticking jobs with t=1587294318.583463
DEBUG      2020-04-19 14:05:18,583 JobQueue                       tick                                 248 : Peeked at hand with t=1587294310.567979
DEBUG      2020-04-19 14:05:18,583 JobQueue                       tick                                 269 : Running job hand
INFO       2020-04-19 14:05:21,583 root                           hand                                 24  : Running 4th time
DEBUG      2020-04-19 14:05:21,584 JobQueue                       _put                                 95  : Putting job hand with t=1587294311.567979
DEBUG      2020-04-19 14:05:21,584 JobQueue                       tick                                 248 : Peeked at hand with t=1587294311.567979
DEBUG      2020-04-19 14:05:21,584 JobQueue                       tick                                 269 : Running job hand
INFO       2020-04-19 14:05:24,588 root                           hand                                 24  : Running 5th time
DEBUG      2020-04-19 14:05:24,588 JobQueue                       _put                                 95  : Putting job hand with t=1587294312.567979
DEBUG      2020-04-19 14:05:24,588 JobQueue                       tick                                 248 : Peeked at important with t=1587294311.568107
DEBUG      2020-04-19 14:05:24,588 JobQueue                       tick                                 269 : Running job important
INFO       2020-04-19 14:05:24,588 root                           important                            29  : important Hello world!
```

**Comment by Bibo-Joshi** [comment] 2020-04-19 11:17
Just to clarify: is this a duplicate of #1338?

**Comment by matveyplevako** [comment] 2020-04-19 11:38
> Just to clarify: is this a duplicate of #1338?

Probably yes, but solving it with threads will introduce additional overhead and it is better to recalculate next timestamp as @MarcelBeining stated https://github.com/python-telegram-bot/python-telegram-bot/issues/1338#issuecomment-468338358

**Comment by Bibo-Joshi** [comment] 2020-04-19 12:39
Okay. TBH, I haven't dived into the discussion, yet. But would you mind, commenting on #1338 with your example? Then we can close this one.

**Closed** 2020-04-19 12:56 UTC
Labels: bug :bug:
