### ISSUE TITLE
parse_caption_entities() fails if there are no entities

### ISSUE THREAD

**Issue by alexbagirov** [python-telegram-bot/python-telegram-bot#1208] opened 2018-09-05 11:49 UTC
### Steps to reproduce
1. `parse_caption_entities()` for caption without entities

### Expected behaviour
Returns empty dictionary.

### Actual behaviour
Throws an error.

### Configuration
**Operating System:** Ubuntu 18.04

**Version of Python, python-telegram-bot & dependencies:**

- Python 3.6.6
- ptb 11.1.0

### Logs
```
An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/alex/Desktop/nmaps-telegram/features/hashtag.py", line 19, in hashtag
    tag = update.message.parse_entity(entity)
  File "/usr/local/lib/python3.6/dist-packages/telegram/message.py", line 838, in parse_entity
    entity_text = self.text.encode('utf-16-le')
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by ehsanonline** [comment] 2018-09-05 16:38
You should check if entity text has value then encode it. Even with an empty dictionary it will gives you similar error:
```
>>> {}.encode('utf-16-le')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'dict' object has no attribute 'encode'
```
My solution:
`entity_text = self.text.encode('utf-16-le') if self.text else ''`

**Comment by alexbagirov** [comment] 2018-09-05 17:47
I see and consider it as a workaround. Probably it would be better to handle it on behalf of ptb. Will be happy to see contributors' opinion :)

**Comment by jsmnbom** [comment] 2018-09-10 13:50
I agree that it should probably not crash if there is no caption.

Easy workaround for now, should be just checking if there is a caption first..

@alexbagirov Your log looks a bit strange though... it doesn't seem like you're using parse_caption_entities at all? At least that's not when it crashes :/

**Comment by Eldinnie** [comment] 2018-10-02 08:33
Both `parse_entities()` and `parse_caption_entities()` do return empty dicts when called when no text/caption is available and also when there's no entities (that match the given type).

In other words it works like you put in expected behavior, and the way it should be. I;m closing this issue, but if you find out something's wrong on our end. Feel free to comment and we'll re-open

**Closed by Eldinnie** 2018-10-02 08:33 UTC

**Comment by jsmnbom** [comment] 2018-10-02 14:18
Yes, this looks like it's probably a matter of using the wrong parse(_caption)?_entities method for the job.
