### ISSUE TITLE
urllib3 HTTPError [Errno 1] _ssl.c:1415: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac

### ISSUE THREAD

**Issue by tapionx** [python-telegram-bot/python-telegram-bot#359] opened 2016-07-26 22:33 UTC
### urllib3 HTTPError [Errno 1] _ssl.c:1415: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac

It happens frequently, when i try to send a message or do others API actions like kick_chat_member
### Configuration

**Operating System: Debian 7**
python telegram bot running over Django with webhook

**Python 2.7**
related dependency:

```
certifi==2016.2.28
cryptography==1.4
ndg-httpsclient==0.4.2
pyOpenSSL==16.0.0
python-telegram-bot==5.0.0
requests==2.10.0
requests-oauthlib==0.6.2
urllib3==1.16
```
### Full Traceback

```
ERROR 2016-07-27 00:15:07,113 Traceback (most recent call last):
  File "./XXX/telegrambot.py", line XX, in wrap
    original_function(bot, update)
  File "./XXX/telegrambot.py", line XXX, in wrap
    original_function(bot, update, XXXX)
  File "./XXX/telegrambot.py", line XXX, in XXX
    bot.sendChatAction(chat_id=chat_id, action=telegram.ChatAction.TYPING)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 121, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 147, in decorator
    result = request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 235, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 166, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
NetworkError: urllib3 HTTPError [Errno 1] _ssl.c:1415: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
```

**Comment by puneetsngh** [comment] 2016-07-30 15:56
Quick fix is add verify=False in requests

**Comment by tapionx** [comment] 2016-07-31 17:03
@puneetsngh that fix does not resolve the issue unfortunately..
I tried to patch the library like this, but the bug still appears:

telegram/utils/request.py, line 50
```
def _init_con_pool():
    global _CON_POOL
    kwargs = dict(maxsize=CON_POOL_SIZE,
    
                  #cert_reqs='CERT_REQUIRED',
                  #ca_certs=certifi.where(),
                  
                  cert_reqs='CERT_NONE',
                  assert_hostname=False,
                  
                  socket_options=HTTPConnection.default_socket_options + [
                      (socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1),
                  ])
```

**Comment by puneetsngh** [comment] 2016-07-31 17:18
Yeah, I realised this after posting, the ae issue occurred with me too as I am too using debian with Python 2.7.3.  The requests module was throwing that error in my case. So it was easy for my to specify verify false. But this module is different so the person written this module will know about this better

**Comment by tapionx** [comment] 2016-09-01 18:01
up! :dancers:

**Comment by tsnoam** [comment] 2017-01-07 21:58
Ok, so I was trying to recreate this one using docker+debian7 and couldn't "just" simply recreate it.
All reports I could find on this error on the internet suggests that this error is unique for debian7 - which if it is makes it "not our problem".
That said, I did see that there were suggestions that this error might be caused by simultaneous usage of the same connection from two different threads.

As I can't rule out the latter I won't close this issue just yet, but rather ask you to provide us with detailed instructions & code snippets on how to recreate the problem.

**Comment by tapionx** [comment] 2017-01-09 08:43
I agree that this problem is not directly related to this project.
The best way to avoid it would be to upgrade to Debian 8, which I will do as soon as possible.
I cannot tell you any step to reproduce this.
We are using python-telegram-bot with webhook over Django 1.9, with virtualenv and uwsgi.

**Comment by tsnoam** [comment] 2017-02-25 20:59
@tapionx 
Sorry for the late reply. Unfortunately we can't support every minor version of python so we'll have to close this issue.
Feel free to reopen if you can provide a procedure to recreate it using the latest python minor version of 2.7/3.3-3.6.

**Closed by tsnoam** 2017-02-25 20:59 UTC
Labels: pending reply
