### ISSUE TITLE
Error get_chat_member for idle users is supergroup

### ISSUE THREAD

**Issue by w33dw0r7d** [python-telegram-bot/python-telegram-bot#1296] opened 2018-11-19 16:36 UTC
### Steps to reproduce
1. Try bot.get_chat_member(chat_id, user_id) in supergroup. For users who doesn't write around a day in group.

### Expected behaviour
Get information about a member of a chat.

### Actual behaviour
BadRequest User_id_invalid.
But after users write message. 
I repeat request and all be fine.

### Configuration
**Operating System:** Linux 

**Version of Python, python-telegram-bot & dependencies:**
python 3.7.1
python-telegram-bot 11.1.0

### Logs
```
BadRequest: User_id_invalid
  File "duck_bot/errorhandler.py", line 34, in _error_callback
    logging.error('Update "%s" caused error "%s"', update, error, exc_info=True, extra={'stack': True, })
  File "telegram/ext/dispatcher.py", line 384, in dispatch_error
    callback(self.bot, update, error)
  File "telegram/ext/dispatcher.py", line 292, in process_update
    self.dispatch_error(update, te)
  File "telegram/ext/dispatcher.py", line 228, in start
    self.process_update(update)
  File "telegram/ext/updater.py", line 156, in _thread_wrapper
    target(*args, **kwargs)
  File "python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
```

**Comment by jsmnbom** [comment] 2018-11-19 18:04
I am 99% sure this is not a bug with the library, but due to how the telegram bot api gateway does user lookups with the telegram api... I'll keep the issue open though, maybe someone else is smarter than me ;)

**Comment by tsnoam** [comment] 2018-11-20 23:04
Hi,

`BadRequest` is a (telegram) server generated error. Therefor it has nothing to do with ptb and I'll be closing this issue.
I suggest you contact bot support about this.

**Closed by tsnoam** 2018-11-20 23:04 UTC
