### ISSUE TITLE
[QUESTION] Unable to add PollHandler in ConversationHandler

### ISSUE THREAD

**Issue by shalabhsingh** [python-telegram-bot/python-telegram-bot#2157] opened 2020-10-21 14:28 UTC
I am working on a bot, where I am asking the user a quiz depending upon the user's previous response. I discovered ```PollHandler``` to handle polls. The issue is that I am unable to use the ```PollHandler``` inside a ```ConversationHandler```

Here is the code-
```
bot_token = TOKEN

def poll_handler(update, context):
    print("Reached poll handler")

def command_handler_start(update, context):
    message = context.bot.send_poll(chat_id=update.message.from_user.id, question="sample question?", \
                          options=["1", "2", "3", "4"], type=telegram.Poll.QUIZ, correct_option_id=2, \
                          explanation="Sample explanation", open_period=15)
    return 1

update = Updater(token=bot_token, use_context=True)
dp = update.dispatcher
```

Now, the ```poll_handler``` function isn't called after attempting the quiz, when I use this-

```
c = ConversationHandler(
	entry_points=[CommandHandler('start', command_handler_start)],
		states={
			1 : [PollHandler(poll_handler)],
		},
		fallbacks=[],
	)
dp.add_handler(c)

update.start_polling()
update.idle()
```

but it get's called, when I use it outside of ```ConversationHandler```- 

```
dp.add_handler(CommandHandler('start', command_handler_start))
dp.add_handler(PollHandler(poll_handler))

update.start_polling()
update.idle()
```

This suggests me that ```PollHandler``` doesn't work with ```ConversationHandler```. Am I doing something wrong or this is the expected behavior? If it's the latter can we please have this feature added?

**Comment by Bibo-Joshi** [comment] 2020-10-21 14:30
Duplicate of #2108 . closing.

**Closed by Bibo-Joshi** 2020-10-21 14:30 UTC
Labels: question
