### ISSUE TITLE
Error in handlers is not shown or handled by default

### ISSUE THREAD

**Issue by avishai-ish-shalom** [python-telegram-bot/python-telegram-bot#1173] opened 2018-07-29 16:58 UTC
### Steps to reproduce
```
def bad_handler(bot, update):
    raise new Error('something bad happened')

updater.dispatcher.add_handler(CommandHandler('boom', bad_handler))
updater.dispatcher.add_error_handler(on_error)
```
Error will not be handled by `on_error` nor printed anywhere unless python logging is configured. This is confusing to users and not properly documented.

### Expected behaviour
Error handler should be either be called or the main documentation (readme, tutorial) should contain a link to the [wiki](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Exception-Handling#other-exceptions) or a section about this.

**Comment by jsmnbom** [comment] 2018-08-11 13:44
@python-telegram-bot/developers ? What do you think? Should arbitrary exceptions raised in handlers be passed to the error handlers?

**Comment by Eldinnie** [comment] 2018-10-02 09:32
I think it's counterintuïtive that they don't.
We have an errorhandler, let it handle errors. Whichever type (instead of only TelegramError)

**Comment by tsnoam** [comment] 2018-10-02 10:34
duplicate of #682

**Comment by Eldinnie** [comment] 2018-10-02 10:39
@tsnoam No it's not

**Comment by tsnoam** [comment] 2018-10-02 21:04
Sorry, my bad. Not a duplicate.
Thinking of it, I suggest the following behavior:
1. In case of unhandled exception (any kind) - if there's a error handler defined - call it.
2. If no error handler is defined: log error the exception.
3. TelegramError may receive prettier logs then unknown errors.

**Comment by nikolaevigor** [comment] 2019-04-02 22:24
Hi, +1 here.

Spent several hours on this. I have configured my own logger, so didn't see exceptions and tracebacks (100% my fault for not seeing it in wiki).
Still, in my opinion any kind of non-Telegram related exceptions should not be suppressed. Or may be it could be an explicit option to suppress it or not.
Version: 12.0.0b1

**Comment by Poolitzer** [comment] 2019-08-29 16:12
This was introduced with #1481 and will be part of the V12 release, thanks for the suggestion.

**Closed** 2019-08-29 16:12 UTC
Labels: enhancement
