### ISSUE TITLE
[BUG] AttributeError: __aenter__

### ISSUE THREAD

**Issue by mdminhaz2003** [python-telegram-bot/python-telegram-bot#3341] opened 2022-11-06 01:00 UTC
### Steps to Reproduce

```

import asyncio
from telegram import Bot
from dotenv import dotenv_values


config = dotenv_values(dotenv_path="./.env")


async def main():
    bot = Bot(token=config.get("BOT_TOKEN"))

    async with bot:
        print(await bot.get_updates()[0])

if __name__ == '__main__':
    asyncio.run(main())

```

### Actual behaviour

```
Traceback (most recent call last):
  File "/home/mdminhaz/PycharmProjects/telegram_bot/main.py", line 16, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/mdminhaz/PycharmProjects/telegram_bot/main.py", line 12, in main
    async with bot:
AttributeError: __aenter__
```

### Operating System

Fedora Linux

### Version of Python, python-telegram-bot & dependencies

```shell
Python Version: 3.10.7
python-telegram-version: 13.14
```

**Comment by Poolitzer** [comment] 2022-11-06 01:02
Hey, this error comes when you did not upgrade to V20 (probably use `pip install --upgrade --pre python-telegram-bot`). But we also have an application and an Updater which does this for you...

**Comment by Bibo-Joshi** [comment] 2022-11-06 14:38
Closing as duplicate of #3040 and #3193

**Closed by Bibo-Joshi** 2022-11-06 14:38 UTC
Labels: bug :bug:
