### ISSUE TITLE
Command Handler with arguments not working with latest Beta

### ISSUE THREAD

**Issue by ice-bit** [python-telegram-bot/python-telegram-bot#1431] opened 2019-06-21 23:33 UTC
### Steps to reproduce
1.  Add a new CommandHandler with arguments enabled(e.g. `pass_args=True`)

2. Call the command along with a parameter

3. It doesn't reply and print a TypeError error

### Expected behaviour
It should call the associated function as described [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Types-of-Handlers#commandhandlers-with-arguments).

### Actual behaviour
It prints this message:
```
TypeError: start_callback() missing 1 required positional argument: 'args'
```

### Configuration
**Operating System:**
Arch Linux

**Version of Python, python-telegram-bot & dependencies:**
```
➜ python -m telegram                     
python-telegram-bot 12.0.0b1
certifi 2019.06.16
future 0.17.1
Python 3.7.3 (default, Mar 26 2019, 21:43:19)  [GCC 8.2.1 20181127]
```

``$ python -m telegram``

### Logs
n/a

**Comment by eugenweissbart** [comment] 2019-06-25 08:14
I can confirm that this is the case.
Traceback:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 333, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
TypeError: start_callback() missing 1 required positional argument: 'args'`

Investigating further

**Comment by eugenweissbart** [comment] 2019-06-25 08:45
Ok, looks like this has to do something with context.
If you initialize an Updater instance with`use_context=True`, this is what happens:
1. In [dispatcher.process_update](https://github.com/python-telegram-bot/python-telegram-bot/blob/39d686b1a1b15d08dd2efb3e20b1ed95d139ae6b/telegram/ext/dispatcher.py#L331) it collects context and passes it to `handler.handle_update`
2. In [handler.handle_update](https://github.com/python-telegram-bot/python-telegram-bot/blob/39d686b1a1b15d08dd2efb3e20b1ed95d139ae6b/telegram/ext/handler.py#L115) is where the weirdness happens. If the context has been passed, it calls callback function with two args: `return self.callback(update, context)`. Otherwise, it calls callback function with three args: `return self.callback(dispatcher.bot, update, **optional_args)`

The question is: is context processing intentionally separated from optional args processing. If so, why the handler doesn't count optional_args existence in [this check](https://github.com/python-telegram-bot/python-telegram-bot/blob/39d686b1a1b15d08dd2efb3e20b1ed95d139ae6b/telegram/ext/handler.py#L115)

I guess this question must go to devs, as for now I haven't found out how can using/not using context interfere with args in CommandHandler. My concern is also why the callbacks differ by first argument used: context-less callback has bot as its first argument and update as second, while context-full callback has update as first and context as second.

**Comment by eugenweissbart** [comment] 2019-06-25 08:52
@jsmnbom could you please help us with that?

**Comment by Eldinnie** [comment] 2019-06-25 09:07
Despite the multiple responses here I'm having trouble understanding what your actual problem is.
Can you please follow the issue template and post a minimal working example to show what your problem is or how to reproduce the error.

Also it seems you might benefit from reading https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0 but I;m not sure, because I'm not sure what your problem is.

**Comment by eugenweissbart** [comment] 2019-06-25 10:51
The code is

```
from telegram.ext import Updater, CommandHandler

updater = Updater(token='123:ABC', use_context=True)
dispatcher = updater.dispatcher


def start_callback(bot, update, args):
    user_says = " ".join(args)
    update.message.reply_text("You said: " + user_says)

dispatcher.add_handler(CommandHandler("start", start_callback, pass_args=True))

updater.start_polling()
```

This doesn't work with `use_context=True`, which is assumed by default. The source of the problem is described by me above.
However this does work with `use_context=False`

**Comment by eugenweissbart** [comment] 2019-06-25 10:54
So for now, `use_context=True` option is incompatible when passing a 3-argument callback to CommandHandler with `pass_args=True`

**Comment by Eldinnie** [comment] 2019-06-25 11:08
Like I said, look at the transition guide. This is not a bug but exactly as it should be.
When using context, do not use `pass_args=True` and the new callback signature,
With `use_context=False` you do it like the old style.

We invite you to ask further questions about the usage of this library in our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Closed by Eldinnie** 2019-06-25 11:08 UTC

**Comment by eugenweissbart** [comment] 2019-06-25 11:13
Ahem, then why this is here?

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Types-of-Handlers#commandhandlers-with-arguments

I install a fresh v12 as it is recommended, so I do not look at transition guide
I open "Your first bot" guide and use `use_context=True` in Updater as stated there
Then I open "Types of handlers" and add a handler with `pass_args=True` as stated there
I get a weird error
I go and report a bug (ok, this was not me)
You say that I should read transition guide but not the documentation.

Rly?

**Comment by Eldinnie** [comment] 2019-06-25 11:23
I'm sorry to say that unfortunately that wiki-page was not updated like every other page as it should have been when we created the v12 bèta.

I now updated the page with the correct new syntax. For more examples of the different handler type. Look at our [examples](https://github.com/python-telegram-bot/python-telegram-bot/tree/master/examples) and the [list of handlers](https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.html#handlers) in the docs.

I'm sorry I misunderstood that the actual question stemmed from a fault in the wiki (Which is not the same as documentation), but in this case, reading the transition guide because [this passage](https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.html#handlers) at the top would have told you what you wanted to know.

**Comment by eugenweissbart** [comment] 2019-06-25 11:25
Thanks for your help!

**Comment by eugenweissbart** [comment] 2019-06-25 11:28
Just a thought – maybe it would be good to add deprecation warning to CommandHandler when using `pass_args` too? That would probably send both of me and @ice-bit to transition guide sooner.

**Comment by ice-bit** [comment] 2019-06-25 11:33
Thanks for your help!
