### ISSUE TITLE
Bot API doesn't support tag <br>

### ISSUE THREAD

**Issue by RibeiroAna** [python-telegram-bot/python-telegram-bot#736] opened 2017-07-22 23:30 UTC
Hello, I was doing a bot using python (2.7.13) and twx.botapi (3.1.1) and I tried to send the following message to the user: 

```
message =  "Something <br> something"
bot.send_message(sender_id, message, reply_markup=reply_markup, parse_mode='HTML').wait() 
```

But I was getting a `400` from the API. I realized that if I changed the `<br>` tag for the python's `\n`, it would work. By the way, I think if I am formating the whole string as HTML, I shouldn't have to use python's string formating style in the middle: so I think it should support the BR tag.

Cheers,
Ana

**Comment by ihoru** [comment] 2017-07-23 03:46
1. `twx.botapi` is another library: https://github.com/datamachine/twx.botapi
2. Anyway, Telegram Bot API supports only these tags: `b`, `i`, `a`, `code`, `pre` (ref: https://core.telegram.org/bots/api#html-style)
But the library does not pre-process for cleaning up text from extra tags, it's your own responsibility.

**Comment by Eldinnie** [comment] 2017-07-23 08:15
Since the problem is with the Bot API, not with our library this is not considered an issue with python-telegram-bot. I'm closing the issue

**Closed by Eldinnie** 2017-07-23 08:15 UTC
