### ISSUE TITLE
Update the apscheduler to the latest version

### ISSUE THREAD

**Issue by mansellrace** [python-telegram-bot/python-telegram-bot#2996] opened 2022-05-05 11:32 UTC
### Issue I am facing

Version 1.6.3 of apscheduler has a bug that causes a job to run twice when using the jitter argument.
Is reported here: https://github.com/agronholm/apscheduler/issues/291

please update apscheduler in this project to fix this bug.

thanks for your work

### Traceback to the issue

```python
2022-05-05 13:17:41,961 - INFO - Running job "Completa, ogni giorno alle 13:18 (+- 2 min) (trigger: cron[day_of_week='0,1,2,3,4,5,6', hour='13', minute='18', second='0'], next run at: 2022-05-05 13:17:41 CEST)" (scheduled at 2022-05-05 13:17:41.957291+02:00)
2022-05-05 13:17:42,180 - INFO - Job "Completa, ogni giorno alle 13:18 (+- 2 min) (trigger: cron[day_of_week='0,1,2,3,4,5,6', hour='13', minute='18', second='0'], next run at: 2022-05-05 13:18:00 CEST)" executed successfully
2022-05-05 13:18:00,003 - INFO - Running job "Completa, ogni giorno alle 13:18 (+- 2 min) (trigger: cron[day_of_week='0,1,2,3,4,5,6', hour='13', minute='18', second='0'], next run at: 2022-05-06 13:17:18 CEST)" (scheduled at 2022-05-05 13:18:00+02:00)
2022-05-05 13:18:00,117 - INFO - Job "Completa, ogni giorno alle 13:18 (+- 2 min) (trigger: cron[day_of_week='0,1,2,3,4,5,6', hour='13', minute='18', second='0'], next run at: 2022-05-06 13:17:18 CEST)" executed successfully
```

### Operating System

Ubuntu server

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.11 (v1.3.0-0-g5f71dc5)
Bot API 5.7
certifi 2021.10.08
Python 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]
```

**Comment by Bibo-Joshi** [comment] 2022-05-05 11:36
Closing as duplicate of #2758

**Closed by Bibo-Joshi** 2022-05-05 11:36 UTC
Labels: question
