### ISSUE TITLE
[BUG] Error while getting updates

### ISSUE THREAD

**Issue by alexx-ftw** [python-telegram-bot/python-telegram-bot#3581] opened 2023-03-08 12:37 UTC
### Steps to Reproduce

I call this function once when starting my program:
```python
async def start_telegram_bot():
    # Add Telegram App Commands
    TELEGRAM_APP.add_handler(  # type:ignore
        telegram.ext.CommandHandler("status", send_telegram_status)  # type:ignore
    )

    # Start Telegram Bot
    await TELEGRAM_APP.initialize()
    await TELEGRAM_APP.updater.start_polling(1)  # type: ignore
    await TELEGRAM_APP.start()
```

Than when the user inputs "0", this other function is called:
```python
async def stop_telegram_bot():
    await TELEGRAM_APP.updater.stop()  # type: ignore
    await TELEGRAM_APP.stop()
    await TELEGRAM_APP.shutdown()
```
### Expected behaviour

The bot should run on the background, polling for updates normally without errors.

### Actual behaviour

Got this two errors:
08-Mar-23 11:32:23.465 - telegram.ext._updater - Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
08-Mar-23 11:32:23.466 - telegram.ext._updater - Exception happened while polling for updates.

### Operating System

Ubuntu 22.04

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.1
Bot API 6.5
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

### Relevant log output

```python
08-Mar-23 11:32:23.465 - telegram.ext._updater - Error while getting Updates: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
08-Mar-23 11:32:23.466 - telegram.ext._updater - Exception happened while polling for updates.
Traceback (most recent call last):
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/h2/connection.py", line 224, in process_input
    func, target_state = self._transitions[(self.state, input_)]
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.SEND_HEADERS: 0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpcore/_async/http2.py", line 106, in handle_async_request
    await self._send_request_headers(request=request, stream_id=stream_id)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpcore/_async/http2.py", line 203, in _send_request_headers
    self._h2_state.send_headers(stream_id, headers, end_stream=end_stream)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/h2/connection.py", line 766, in send_headers
    self.state_machine.process_input(ConnectionInputs.SEND_HEADERS)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/h2/connection.py", line 228, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpcore/_async/http2.py", line 142, in handle_async_request
    raise LocalProtocolError(exc)  # pragma: nocover
httpcore.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 199, in do_request
    res = await self._client.request(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
    if not await action_cb():
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
    raise exc
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
    updates = await super().get_updates(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/_bot.py", line 3510, in get_updates
    await self._post(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 274, in _request_wrapper
    code, payload = await self.do_request(
  File "/root/MasterPanel/.env/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 223, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED
```

### Additional Context

i am not using the ".run_polling()" as I have my own loop on my code.

**Comment by Bibo-Joshi** [comment] 2023-03-08 19:50
Closing as duplicate of #3556

**Closed by Bibo-Joshi** 2023-03-08 19:50 UTC
Labels: bug :bug:

**Comment by alexx-ftw** [comment] 2023-03-08 20:39
> Closing as duplicate of #3556

Hey so how am I supposed to fix this?

**Comment by Bibo-Joshi** [comment] 2023-03-08 20:41
Setting the http version to 1.1 as descriped e.g. here https://github.com/python-telegram-bot/python-telegram-bot/issues/3556#issuecomment-1435928383 should do the trick
