### ISSUE TITLE
sending photo to channel by job_queue

### ISSUE THREAD

**Issue by mohamad29175** [python-telegram-bot/python-telegram-bot#717] opened 2017-07-12 10:05 UTC
### Steps to reproduce
1. I made a job_queue and try to send photo to my channel.

2. when doing this with my other project it works. But in this new project it sends my file_id instead of the photo itself.

### Expected behaviour
send photo that I give to my bot.

### Actual behaviour
send my photo file_id

### Configuration
**Operating System:**

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``

### Logs
job.context = [username, photo[-1].file_id, caption)

bot.sendPhoto(chat_id=job.context[0], photo=job.context[1], caption=job.context[2])

**Comment by Eldinnie** [comment] 2017-07-23 08:17
Is this issue still live? Can you share a minimal working example to reproduce so we can see where the problem lies and address the issue?

**Comment by bomjacob** [comment] 2017-07-29 16:42
Closing due to no reply, and lack of following issue template (no logs)

**Closed by bomjacob** 2017-07-29 16:42 UTC
Labels: pending reply
