### ISSUE TITLE
need help to set webhook

### ISSUE THREAD

**Issue by ehsankhorasani** [python-telegram-bot/python-telegram-bot#836] opened 2017-09-18 10:50 UTC
Hi
By Django I build a site for booking a room. users can be used both through the site and the telegram (bot).
When I use ```updater.start_polling()``` bot work well.
but I need to use webhook.
in my bot I use this snippets:
```
    updater.start_webhook(listen = "0.0.0.0",
                          port = 443,
                          url_path = '/')
    updater.bot.setWebhook("https://xxx.com/")
```

and in my nginx config:

```
server {
        listen 80;
        listen [::]:80;
        server_name xxx.com;

        location /static/ {
                root xxxx;
        }

        location / {
                proxy_pass http://unix:/xxx/reservation.sock;
        }

}
```
but my bot not work in webhook.
can you help me?

**Comment by jh0ker** [comment] 2017-09-18 11:38
@ehsankhorasani In your nginx config you are listening on port 80, but it should be port 443

**Comment by ehsankhorasani** [comment] 2017-09-18 12:21
@jh0ker but why the robot works on Port 80 in ```updater.start_polling()```?

**Comment by ehsankhorasani** [comment] 2017-09-18 12:21
Because I use Cloudflare ssl, I cant use port 443

**Comment by jh0ker** [comment] 2017-09-18 12:47
@ehsankhorasani Okay, but then why are you listening on port 443 in start_webhook?

**Comment by ehsankhorasani** [comment] 2017-09-18 21:00
@jh0ker I found my mistake and change port to 80
but steel not work

**Comment by jh0ker** [comment] 2017-09-19 09:36
@ehsankhorasani I see. And what is the the meaning of the location / entry?

**Comment by jh0ker** [comment] 2017-09-21 19:16
Have you been able to fix the problem or gather some more information on it? Perhaps you can check the `nginx` logs to see if the problem is in your `nginx` config or somewhere else. If the problem is already solved, please close this issue.

**Comment by ehsankhorasani** [comment] 2017-09-23 08:55
I'm sorry for the delay in responding
what's the meaning of the location / entry?
like this:
```
location /TOKEN1 {
        proxy_pass http://127.0.0.1:5000;
    }
```
Because I have one bot, and I use `url_path='/'` in `start_webhook`

**Comment by ehsankhorasani** [comment] 2017-09-23 08:57
In nginx log every things are Ok
all log line like these lines:
```
141.101.98.41 - - [23/Sep/2017:11:37:47 +0330] "POST / HTTP/1.1" 200 22 "-" "-" "149.154.167.229"
141.101.98.41 - - [23/Sep/2017:11:37:49 +0330] "POST / HTTP/1.1" 200 22 "-" "-" "149.154.167.229"
```

**Comment by ehsankhorasani** [comment] 2017-09-23 08:58
how can I save log for `start_webhook` in bot?

**Comment by programmingvenkat** [comment] 2017-09-23 09:15
Try removing `updater.start_polling()`

**Comment by programmingvenkat** [comment] 2017-09-23 09:15
Webhooks usually timeout if you use that @ehsankhorasani

**Comment by ehsankhorasani** [comment] 2017-09-23 09:46
@programmingvenkat I've already deleted it

**Comment by Eldinnie** [comment] 2017-09-29 12:00
What's the status on this? @ehsankhorasani have you figured out if the problem is with the library or other configurations?

**Comment by ehsankhorasani** [comment] 2017-10-02 06:18
@Eldinnie yes
I solve it

**Comment by Eldinnie** [comment] 2017-10-02 13:23
Ok, good to hear, closing the issue then.

**Closed by Eldinnie** 2017-10-02 13:23 UTC

**Comment by pourya2374** [comment] 2017-10-21 13:47
@ehsankhorasani 
how did you solve it?

**Comment by ehsankhorasani** [comment] 2017-10-22 07:46
@pourya2374 
I use this package [django-telegrambot](https://github.com/JungDev/django-telegrambot) in django
but when I saw the code of this package, I realized that it was using [Custom solution webhook](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Webhooks#custom-solution)
