### ISSUE TITLE
[BUG] Possibility of `Event loop is closed` warning after Bot shutdown

### ISSUE THREAD

**Issue by harshil21** [python-telegram-bot/python-telegram-bot#2997] opened 2022-05-05 14:51 UTC
While testing our code, we [became aware](https://github.com/python-telegram-bot/python-telegram-bot/pull/2925#discussion_r862607322) that there could be a chance that we get an `Event loop is closed` error _after_ shutting down the bot. This seems to only affect Windows and python versions 3.8+ and is related to `ProactorEventLoop` event loop policy on Windows.

#### MRE:
``` python
from telegram import Bot
import asyncio

async def bot_initialize():
    bot = Bot("TOKEN")
    await bot.initialize()

asyncio.run(bot_initialize())
```

The problem is most likely not with our library but with CPython itself, see https://github.com/python/cpython/issues/83413 and https://github.com/encode/httpx/issues/914.

A workaround would be to switch our default event loop policy to `WindowsSelectorEventLoopPolicy`, which is now what we do in tests. If multiple users are facing this problem frequently, we could consider switching.

If anybody is willing to dig into this further and figure out when/how/why exactly this error occurs, that would be great. 

### Python versions affected:

`3.8, 3.9`

**Comment by harshil21** [comment] 2022-06-30 21:45
Closing since this is fixed upstream:  https://github.com/python/cpython/issues/92841#issuecomment-1171644047
on python 3.10 and 3.11.

**Comment by Poolitzer** [comment] 2022-06-30 21:55
@harshil21 But we support versions lower then 10, and they can see that error. I would either set the proper event loop or throw a warning if it isn&#x27;t set on the non fixed versions

**Comment by harshil21** [comment] 2022-06-30 21:58
@Poolitzer chances that someone bumps into this are rare, so far I&#x27;ve seen this happen due to another (unrelated) error happening. So I don&#x27;t think we need to take any action just yet.

**Comment by tsnoam** [comment] 2022-07-02 07:32
@Bibo-Joshi Is there a real problem here? Data loss? Or is it just an annoying log at shutdown time?

If the latter and the problem is with python I think that closing as wontfix is appropriate.

**Comment by Bibo-Joshi** [comment] 2022-07-03 13:19
@tsnoam I&#x27;m not entirely sure tbh. would have to double check …

**Comment by Bibo-Joshi** [comment] 2022-07-07 16:43
I can't find any indication that the unexpected shutdown happens before any shutdown logic. In fact, while I can reproduce the issue with the example from above (where `Bot.shutdown` is not called!), running 

```python
from telegram import Bot
import asyncio


async def bot_initialize():
    async with Bot("TOKEN"):
        pass


asyncio.run(bot_initialize())
```

where we properly shut down the bot, the error does not appear. Hence, it looks like the problem only happens if the user doesn't properly free resources in the first place. Hence, I'll close as wontfix.

Still, if someone comes across the issue in a more sane setting, we should definitely reopen.

**Closed by Bibo-Joshi** 2022-07-07 16:43 UTC
Labels: bug :bug:, windows
