### ISSUE TITLE
Error when send notification

### ISSUE THREAD

**Issue by SaidtheBoss** [python-telegram-bot/python-telegram-bot#1929] opened 2020-04-30 07:47 UTC
### Issue I am facing
When there are small amount of users i have no problem but when the amount gets larger like 50+ then i cant send notification
### Traceback to the issue
my code takes the user id and puts it on a set 
put it here
```python
def start(update, context,d = True):
    user_id = update.message.from_user.id
    print(user_id)
    global id_number
    id_number.add(str(user_id))
```
and when i send command /Notif
```python
def notifsender(update,context):
    print("notification")
    global datanotif
    datanotif = pd.read_csv("notif.csv")
    global id_number
    Link = datanotif['pic'].values
    Link = str(Link[0])
    text = datanotif['text'].values
    text = str(text[0])
    for i in list(id_number):
        bot.send_photo(chat_id=i, photo=Link)
        context.bot.send_message(chat_id=i, text=text)
```
(my code takes notification and pic from file)
When there are like 10 users i can send notification to all the users  but when i have 25 users its not sending notifications even to me

**Comment by Bibo-Joshi** [comment] 2020-04-30 07:55
Well, without actual error traceback, I can only guess, but the guess would be that you're hidding [flood limits](url). We have a [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits) for that.

Also, you may want to use `bot_data` ([here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data)) instead of global variables.

**Comment by SaidtheBoss** [comment] 2020-04-30 08:35
so is there a proper way i can send notification to all my users?

**Comment by SaidtheBoss** [comment] 2020-04-30 08:37
> Well, without actual error traceback, I can only guess, but the guess would be that you're hidding [flood limits](url). We have a [wiki page](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits) for that.
> 
> Also, you may want to use `bot_data` ([here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Storing-bot,-user-and-chat-related-data)) instead of global variables.

so is there a proper way i can send notifications to all my users?

**Comment by SaidtheBoss** [comment] 2020-04-30 08:38
And is there away i can delay messages?

**Comment by SaidtheBoss** [comment] 2020-04-30 08:41
`def notifsender(update,context):
    print("notification")
    global datanotif
    datanotif = pd.read_csv("notif.csv")
    global id_number
    Link = datanotif['pic'].values
    Link = str(Link[0])
    text = datanotif['text'].values
    text = str(text[0])
    for i in list(id_number):
        bot.send_photo(chat_id=i, photo=Link)
        context.bot.send_message(chat_id=i, text=text)`
how can i edit this code so it would avoid Floodgate limit?

**Comment by SaidtheBoss** [comment] 2020-04-30 08:41
thanks in advance :)

**Comment by Bibo-Joshi** [comment] 2020-04-30 08:43
As for flood limits: See my previous comment.
Sending to all users: See #1836. As this is in fact pretty much a duplicate of that, I'll be closing this one.

Also, please don't comment like you're on an instant messenger. It clutters the thread and there are people, who receive an E-Mail every time you comment.

**Closed by Bibo-Joshi** 2020-04-30 08:43 UTC
Labels: question
