### ISSUE TITLE
timeout behavior and kwargs in conversationhandler

### ISSUE THREAD

**Issue by Eldinnie** [python-telegram-bot/python-telegram-bot#1250] opened 2018-10-11 07:21 UTC
In `ConversationHandler` we have quite a lot of kwargs regarding `@run_async` decorated handler callbacks and timeouts.
these are:

- `run_async_timeout` - The time conversationhandler will wait on a run_async task to complete.
- `timed_out_behavior` - Here you can specify a list of handlers that will handle the new update if the timeout is exceeded but nog finished on a `@run_async` decorated callback
- `conversation_timeout` - If this value is exceeded the conversation will be ended (with an internal job)

in v12 we add a mechanic to give the user an interaction with the conversation on 
- `conversation_timeout` by adding a `TIMEOUT` state which will be offered the last received update.

Now while debugging I noticed the following things that are a bit off.
If I specify a `run_async_timeout=5` it should mean that if the decorated handler takes longer then 5 seconds it will switch to `timed_out)behavior` but this is not the case.
The waiting for it to complete starts on an incomming new update, within `check_update`. This means a couple of bad things.

- If I set a timeout for 10 seconds. It could still be running for 3 days and 10 seconds if the next update is only received after 10 days
- If I specify a `run_async_timeout=20` and the handler is doing something infinite. The processing of the `update_queue` will be paused for 20 seconds while waiting.
- see this example: https://gist.github.com/Eldinnie/a94f313eb74d7d1ef8579a514f18f1a4 If you send /start -> /brew it will timeout (which will set the state to END) but after 20 seconds it will still send the message from brew

I also think `timed_out_behavior` is badly named. From the name I would expect whatever is in there to happen when it's timedout (especially with the `conversation_timeout` also an argument)

Question:
Why was `run_async_timeout` and `timed_out_behavior` added, and mostly do we still need it with the new mechanics?
Is it possible to stop a promise from running if timeout is reached?

Proposal.
Remove `run_async_timeout` and `timed_out_behavior` kwargs and functionality. I think it's superseeded with the newer timeout mechanics.

**Comment by jsmnbom** [comment] 2018-10-11 19:02
I'm not sure if new timeout behaviour superseeds run_async_timeout and timed_out_behavior.
conversation_timeout will usually be set to something like a couple of hours right, and is the timeout where conversationhandler forgets about a state.
run_async_timeout on the other hand is often set to 30, 60 or 120 (based on a non exhaustive github code search - note: only about 5 bots on github use it, out of literally 1000s) and is how long to wait a run_async promise to be resolved (so we can get the new state) before giving up.

`Is it possible to stop a promise from running if timeout is reached?`
No, it isn't, but run_async_timeout and timed_out_behavior is simply how long time before conversationhandler gives up

No matter what we need to do _something_, having two different timeouts like we currently do is way too confusing (especially with current names). I do think they are both useful though, but seeing as most users will probably use the TIMEOUT state to send a message like "Ooops, conversation timed out, please try again.", I think we could remove timed_out_behavior and instead use TIMEOUT state like conversation_timeout does.
This would keep both run_async_timeout and conversation_timeout but I don't think those can be confused too badly (especially with good docs).

**Comment by Eldinnie** [comment] 2018-10-11 19:06
@jsmnbom Ok. So regarding your solution. Then what happens when run_asyc_timeout is exceeded.

Also can you share what you think about the run_async_timeout only starting on a new update and clogging up the update queue?3

**Comment by jsmnbom** [comment] 2018-10-11 19:08
`Then what happens when run_asyc_timeout is exceeded.`
I'd say it should have the same behaviour as conversation_timeout - that is, it should use TIMEOUT as the state, and look up handlers etc.

`Also can you share what you think about the run_async_timeout only starting on a new update and clogging up the update queue?3`
That... is actually very bad... makes me wish we used asyncio or smth similar :/´
But at most it'll block a single out of 4 (by default) worker threads right? - Like it's bad, but it's not like the whole bot is blocked?

**Comment by Eldinnie** [comment] 2018-10-11 19:10
@jsmnbom Actually it is. The update_queue is processed in a single thread. The handler is working in one of 4 workers, but the entire update_queue is paused while dispatcher.process_update is waiting for the ConversationHandler.check_update to return

**Comment by jsmnbom** [comment] 2018-10-11 19:13
Okay I see... that is veeery bad then. But I don't see any way of handling that? Other than delegating work to the worker threads even sooner than we do now, which seems like a big change (especially for something that evidently hasn't really been an issue?)

**Comment by jh0ker** [comment] 2018-10-12 06:57
@jsmnbom is correct about the reason why we introduced `run_async_timeout`. We needed a way to handle promises running very long. `timed_out_behavior` was introduced to react to this by telling the user something like "Please try again in a bit, I'm still working on it"

I agree though, the implementation is problematic and the documentation is insufficient. I see two options to improve:

1. Removing `run_async_timeout` and change the logic as if it's always 0. That way, we never clog up the bot and we can still allow the bot to handle timeouts. Rename `timed_out_behavior` to something more obvious.
2. Whenever we run a promisfied handler, we also save a current timestamp (either in the `Promise` or the state dict). That way, we can at least calculate the total elapsed time.

I would probably prefer 1.

Running `Dispatcher.process_update` aync already would make all handlers run async by default and potentially introduce concurrency issues. As @jsmnbom mentioned, it doesn't seem to be worth it.

**Comment by Eldinnie** [comment] 2018-10-29 10:34
Ok so to conclude this before making code changes.
My proposal is to make `ConversationHandler` get this behavior:

remove `run_async_timeout` and `timed_out_bahavior` arguments.
change the `_triggger_timeout` behavior to make it possible for handlers in there to return a new state (for example return to main menu)
when a new update is received (in check_update) and last state was a Promise. check `new_state.don.is_set()` if not, handle the NEW update accoring to the `TIMEOUT` state. (this will also remove the running timeout job which is an added benefit).

any objections, corrections or additions?

**Comment by jsmnbom** [comment] 2018-10-31 10:56
Wouldn't this mean that if say update one takes 1 sec to complete, and you receive another update 0,5 after the first one was received, the new update is handled according to TIMEOUT?

**Comment by Eldinnie** [comment] 2018-10-31 11:04
@jsmnbom Yes, but if we implement the possiblity to return a new state in timeout that might be acceptable?

**Comment by jsmnbom** [comment] 2018-10-31 11:21
I still think it would be kinda odd behaviour.. and it would make conversationhandler + run_async basically useless in popular bots

**Comment by Eldinnie** [comment] 2018-10-31 11:25
@jsmnbom I think it makes conversationhandler + run_async + impatient users is a bad combination. The popularity of the bot shouldn't make the difference.
I'm open to other suggestions though, if you have them

**Comment by jsmnbom** [comment] 2018-11-01 20:51
I don't really have any other suggestions, but I think your suggestion could be a regression for a good portion of users, which isn't very optimal.
To me it's quite common behaviour for a user, to send another command/msg if they didn't receive immediate (~1sec) feedback for the first one.

**Comment by Eldinnie** [comment] 2018-11-05 07:55
It seems I misread @jh0ker 's idea.
Next design idea.
Add a state possibility `WAITING` to Conversationhandler. and remove the `timed_out_bahavior` and `run_async_timeout` argument. Default the timeout to `0` and if not done yet use the handlers in `WAITING`.
Handlers in `WAITING` and `TIMEOUT` can still return new states.

**Comment by jsmnbom** [comment] 2019-02-13 22:01
> I still vote for
> - ConversationHandler.TIMEOUT -> List of handlers used on the last received update when the
 ConversationHandler.conversation_timeout is exceeded (already implemented now)
> - remove run_async_timeout and timed_out_behavior parameters.
> - Add ConversationHander.WAITING as a constant. (-3) can be used in the state dict.

@Eldinnie 

Alright, that seems like an okay solution to me if I understand it right.
WAITING would only ever happen when using run_async right?
Could one implement a run_async_timeout by sleeping in a WAITING handler? I guess not right, since there's no way to know the original state to return?
TIMEOUT in this solution is ONLY triggered by exceeding conversation_timeout right?

**Comment by Eldinnie** [comment] 2019-02-13 22:04
@jsmnbom `WAITING` will be for receiving a new message while the previous `@run\_async` decorated handler is not yet finished and has not yet returned a new state
yes, you can use that to extend the wait, by simply not doing anything, or only passing the message it;s not ready yet. It will not change states any more then `timed\_out\_behavior` does now.
`TIMEOUT` will then solely and only be for an exceeding of `conversation\_timeout`

**Comment by jsmnbom** [comment] 2019-02-13 22:07
> yes, you can use that to extend the wait, by simply not doing anything, or only passing the message it;s not ready yet. It will not change states any more then `timed\_out\_behavior` does now.

But don't you need to return a state from the WATING handler after you've slept?

**Comment by jsmnbom** [comment] 2019-02-13 22:09
Honestly nvm, this is such a weird usecase that assumes people still need run_async_timeout, which probably isn't the case (and should probably be fixed in their code elsewhere - aka why the hell is my handler so slow anyway).
So the proposed solution sounds good to me :)

**Closed** 2019-02-14 12:57 UTC
