### ISSUE TITLE
networkError when entering first update

### ISSUE THREAD

**Issue by diakbar** [python-telegram-bot/python-telegram-bot#289] opened 2016-05-11 14:45 UTC
just installed on fresh ubuntu but got this error, anyone knows this?
```

2016-05-11 22:42:38,349 - telegram.bot - DEBUG - Entering: getUpdates
Traceback (most recent call last):
  File "echobot.py", line 56, in <module>
    main()
  File "echobot.py", line 21, in main
    update_id = bot.getUpdates()[0].update_id
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 114, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1315, in getUpdates
    result = request.post(url, data, timeout=urlopen_timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 83, in decorator
    raise NetworkError('URLError: {0}'.format(error.reason))
telegram.error.NetworkError: URLError: ('_ssl.c:574: The handshake operation timed out',)

```

**Comment by jh0ker** [comment] 2016-05-11 14:51
Closing as duplicate of #283

**Closed by jh0ker** 2016-05-11 14:51 UTC
