### ISSUE TITLE
Segfault during installation with pip on Raspberry Pi

### ISSUE THREAD

**Issue by aDogCalledSpot** [python-telegram-bot/python-telegram-bot#1292] opened 2018-11-12 18:10 UTC
Building from source works. But using pip as in the README will lead to a SEGFAULT.

### Steps to reproduce
1.  Install dependencies `sudo apt install gcc libffi-dev libssl-dev python-dev`

2.  `pip install python-telegram-bot --upgrade`

### Expected behaviour
The program is correctly installed on an RPi

### Actual behaviour
After saying that the script has successfully installed all the packages an additional line saying
`Segmentation fault` will display and the packages will in fact not have been installed (easy to test by running a simple bot)

### Configuration
Raspbian Stretch

**Version of Python, python-telegram-bot & dependencies:**
Python 2.7.3 and Python 3.5.3 both fail the installation in the same way when using pip and pip3 respectively.

Pip is version 9.0.1

### Logs
Last lines of running pip:
```
Successfully built cryptography
Installing collected packages: certifi, asn1crypto, pycparser, cffi, idna, six, enum34, ipaddress, cryptography, future, python-telegram-bot
Successfully installed asn1crypto-0.24.0 certifi-2018.10.15 cffi-1.11.5 cryptography-2.4.1 enum34-1.1.6 future-0.17.1 idna-2.7 ipaddress-1.0.22 pycparser-2.19 python-telegram-bot-11.1.0 six-1.11.0
Segmentation fault
```

**Comment by tsnoam** [comment] 2018-11-12 18:58
@aDogCalledSpot Hi,
That's a very weird error which seems related to your specific environment.
Nevertheless, lets make sure of it:
1. Please run pip with the maximum verbosity and attach the logs 
2. Please supply a core dump of the crash.
3. Run `strace -f -yy -s 9999 -o /tmp/strace.out pip .... ` and attach the `strace.out` file here.

**Comment by aDogCalledSpot** [comment] 2018-11-12 22:05
1. I ran pip with maximum verbosity and tried to output to a log file. I  didn't have the permissions to write to a log file in my home folder so I reran with sudo and then I didn't get a segfault. I reinstalled a few times and can confirm that using sudo works.

2. The core doesn't seem to be getting dumped. Otherwise it should say `Segmentation fault (core dumped)`, right?

3. [Here you go](https://github.com/python-telegram-bot/python-telegram-bot/files/2573808/strace.out.zip)

**Comment by tsnoam** [comment] 2018-11-13 05:16
@aDogCalledSpot 
As installing your package using a different environment (i.e. from root) does not have the same problem, it's now clear the problem is with your environment.

You might want to take a look at the following reports which seems related:
https://bitbucket.org/cffi/cffi/issues/272/segfault-while-installing-via-pip
https://bugs.python.org/issue27542

By reviewing your strace, I would suspect it's one of the following `.so` files:
```
/home/pi/.local/lib/python3.5/site-packages/_cffi_backend.cpython-35m-arm-linux-gnueabihf.so
/home/pi/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/_constant_time.abi3.so
/home/pi/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
/home/pi/.local/lib/python3.5/site-packages/cryptography/hazmat/bindings/_padding.abi3.so
```
About the coredump, in order to produce it you should unlimit the core dump size: `ulimit -c unlimited`.

Anyway, I'm closing this issue for the reason I've started with: it's clearly an environment issue and not a problem with PTB.

**Closed by tsnoam** 2018-11-13 05:16 UTC
