### ISSUE TITLE
Job not executed by run_once if when=0 

### ISSUE THREAD

**Issue by marco-venuti** [python-telegram-bot/python-telegram-bot#1719] opened 2020-01-21 09:34 UTC
### Steps to reproduce
Call for instance
`updater.job_queue.run_once(<something>, 0)`

### Expected behaviour
`<something>` should be called immediately.

### Actual behaviour
Raises
```ValueError("no time specification given for scheduling non-repeating job")```
I blame https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/jobqueue.py#L98 for this.
This is actually executed as
```time_spec = 0 or None```
which evaluates to `None` instead of `0` which should be more appropriate in this circumstance.

### Configuration
Debian stretch 9.11
python-telegram-bot 12.3.0

**Comment by Bibo-Joshi** [comment] 2020-02-03 18:02
Fixed by #1707, can't reproduce on master.

**Closed by Bibo-Joshi** 2020-02-03 18:02 UTC
Labels: bug :bug:
