### ISSUE TITLE
Error:  raise TimedOut() When send Bot message. 

### ISSUE THREAD

**Issue by VuDn5** [python-telegram-bot/python-telegram-bot#1287] opened 2018-11-05 08:07 UTC
Dear python-telegram-bot,
1.  i install python-telegram-bot  by command 
`
pip install python-telegram-bot
`

2.    i have a loot (about 267times) to send json string: {"APID":1,"APMAC":"ac:ad:ad:er:xx:xx"}

`
bot = telegram.Bot(token='xxxxxxxxx:AAE51mDv0oxdxxxxxxxcxxxxxxxxxx')
listAp = jsontring
for apId in listAp:
      bot.send_message(chat_id=chat_id,text=apId,timeout =10000)
`
3.  But sometime send done, sometimes send fail with log file below:

`
Traceback (most recent call last):
  File "warning_chanel.py", line 97, in <module>
    bot.send_message(chat_id=chat_id,text=apId,timeout =10000)
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/lib/python2.7/site-packages/telegram/utils/request.py", line 205, in _request_wrapper
    raise TimedOut()
`

4. My OS is Cent OS 7, python version: Python 2.7.5,  
`
python-telegram-bot 11.1.0
certifi 2018.08.24
future 0.17.1
Python 2.7.5 (default, Jul 13 2018, 13:06:57)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
`

5. What can i do to fix it?  and  i guest it's a bug?
thanks for your help!

**Comment by jsmnbom** [comment] 2018-12-28 12:45
This is likely not a bug, but instead something with either your setup or telegrams infrastructure. Please direct further questions to our [Telegram group](https://t.me/pythontelegrambotgroup). In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.

Since this system is for tracking issues with the library itself, we'll be closing this one.

**Closed by jsmnbom** 2018-12-28 12:45 UTC
