### ISSUE TITLE
[BUG] `InlineKeyboardMarkup` does not appear with `send_photo()`

### ISSUE THREAD

**Issue by kmfrick** [python-telegram-bot/python-telegram-bot#4229] opened 2024-05-02 08:49 UTC
### Steps to Reproduce

1. Run the following code in a scope where a `context` object is available:
```python
img_stream = open("/path/to/image.png", "rb")
user_id = 55555555
buttons = [
InlineKeyboardButton(
                    "A",
                    callback_data=str(
                        {
                            "test": "test1",
                        }
                    ),
                ), 
InlineKeyboardButton(
                    "B",
                    callback_data=str(
                        {
                            "test": "test2",
                        }
                    ),
                )
]
mkp = InlineKeyboardMarkup([buttons])
await context.bot.send_photo(
                chat_id=user_id,
                photo=img_stream,
                reply_markup=mkp,
            )
```

### Expected behaviour

I receive a photo with two buttons underneath.

### Actual behaviour

I receive just the photo.

### Operating System

Linux 5.4.0-177-generic #197-Ubuntu SMP Thu Mar 28 22:45:47 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 21.1.1
Bot API 7.2
Python 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
```

**Comment by kmfrick** [comment] 2024-05-02 09:02
I have the await in my code, I forgot to await the function when I was writing an MWE. Correcting there.

**Comment by Bibo-Joshi** [comment] 2024-05-09 07:08
I can't reproduce either. MWE:

<details>

```python
import asyncio
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Bot


async def main():
    img_stream = open("tests/data/game.png", "rb")
    user_id = 1145108092
    buttons = [
        InlineKeyboardButton(
            "A",
            callback_data=str(
                {
                    "test": "test1",
                }
            ),
        ),
        InlineKeyboardButton(
            "B",
            callback_data=str(
                {
                    "test": "test2",
                }
            ),
        ),
    ]
    mkp = InlineKeyboardMarkup([buttons])

    async with Bot("TOKEN") as bot:
        await bot.send_photo(
            chat_id=user_id,
            photo=img_stream,
            reply_markup=mkp,
        )

if __name__ == "__main__":
    asyncio.run(main())
```

</details>

Closing.

**Closed by Bibo-Joshi** 2024-05-09 07:08 UTC
Labels: bug :bug:
