### ISSUE TITLE
Videos are black on TelgramX IOS - just hearing sound

### ISSUE THREAD

**Issue by omidraha** [python-telegram-bot/python-telegram-bot#1361] opened 2019-03-07 12:49 UTC
Hi,

I download a video from YouTube:

`$ youtube-dl -f 18  https://www.youtube.com/watch?v=FL22h3Qka_c`

The info about this format:

```
$ youtube-dl -F  https://www.youtube.com/watch?v=FL22h3Qka_c | grep 18
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
```

And then sent it to channel with bot:

```
bot = telegram.Bot(token=token)
bot.sendVideo(chat_id=chat_id,
    video=video,
    caption=caption,
    duration=duration,
    thumb=thumb)
```

Video will play very well on Telegram of Android, but when playing on Telegram IOS it's a black screen with voice.

If I save the video to gallery from the channel, the video will be play very well with default video player of IOS.

Also I try to convert video (related issue [here](https://github.com/peter-iakovlev/Telegram/issues/85#issuecomment-466261051))  but I have same problem.

Also I report this [here](https://github.com/peter-iakovlev/TelegramCore/issues/50).

Any idea?

Thanks.

---
1. What version of pyTelegramBotAPI are you using?

`python-telegram-bot==11.1.0`

2. What OS are you using?
`
Ubuntu server 18.04`

3. What version of python are you using?
`Python  2.7.12`

**Comment by Eldinnie** [comment] 2019-03-07 13:41
To me it sounds like a problem with the telegram app on osX, not with our library. If it sends ok, and can be played in other clients but not osX, the problem is with the client.
My guess is that Apple doesn't like th AVC, codecs.

I'm closing this issue for not being a problem with our library.

P.S. Do yourself a favor and switch off py2 ;-)

**Closed by Eldinnie** 2019-03-07 13:41 UTC

**Comment by omidraha** [comment] 2019-03-07 14:56
Thank you for your reply,
Do you know Apple like which format codec?
Also when I save the file from channel to gallery and open it with default Apple Player, video will be played. but within the Telegram X  video is black.
```

[info] Available formats:

format code  extension  resolution note
249          webm       audio only DASH audio   47k , opus @ 50k, 1.47MiB
250          webm       audio only DASH audio   61k , opus @ 70k, 1.85MiB
251          webm       audio only DASH audio  115k , opus @160k, 3.46MiB
171          webm       audio only DASH audio  116k , vorbis@128k, 3.29MiB
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k, 4.51MiB
278          webm       256x144    144p  101k , webm container, vp9, 30fps, video only, 3.29MiB
160          mp4        256x144    144p  134k , avc1.4d400c, 30fps, video only, 3.32MiB
242          webm       426x240    240p  220k , vp9, 30fps, video only, 6.71MiB
133          mp4        426x240    240p  278k , avc1.4d4015, 30fps, video only, 7.53MiB
243          webm       640x360    360p  417k , vp9, 30fps, video only, 12.45MiB
134          mp4        640x360    360p  634k , avc1.4d401e, 30fps, video only, 14.72MiB
244          webm       854x480    480p  714k , vp9, 30fps, video only, 22.89MiB
135          mp4        854x480    480p 1178k , avc1.4d401f, 30fps, video only, 26.09MiB
247          webm       1280x720   720p 1564k , vp9, 30fps, video only, 48.87MiB
136          mp4        1280x720   720p 2381k , avc1.4d401f, 30fps, video only, 54.95MiB
248          webm       1920x1080  1080p 2725k , vp9, 30fps, video only, 89.12MiB
137          mp4        1920x1080  1080p 4678k , avc1.640028, 30fps, video only, 103.29MiB
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

**Comment by Eldinnie** [comment] 2019-03-07 14:57
I don't know, Apple products are a mystery to me.
But as I said it's a problem with the osX client not our lib, so please ask your questions there.

**Comment by hisirbr** [comment] 2020-05-23 18:59
https://github.com/TelegramMessenger/Telegram-iOS/issues/301
