### ISSUE TITLE
Issue on sendPhoto

### ISSUE THREAD

**Issue by gibosler** [python-telegram-bot/python-telegram-bot#239] opened 2016-04-18 13:53 UTC
Hi, 
i've an issue trying to sendPhoto with bot. I've tryped many combinations of configuration without results.
I'm using your libs downloaded and imported in my script. I'm using virtualenv with python 2.7.9
When i'll try to sendPhoto with code:
`bot.sendPhoto(chat_id=update.message.chat_id, photo=open('/tmp/phchart.png', 'rb'))`

i receive the error:

> [...]/inputfile.py", line 165, in _parse
    return '\r\n'.join(form)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 0: ordinal not in range(128)

I'm using in venv because i'm planning to use with django as a backend to configure/store/monitor my bot. 
Thank's in advance for your help.

**Comment by jh0ker** [comment] 2016-04-18 13:55
Photos should be in JPEG format, it might be related to that. If you can, please give it a try.

**Comment by leandrotoledo** [comment] 2016-04-18 14:14
@gibosler Could you post the image somewhere so we can try to reproduce?

**Comment by gibosler** [comment] 2016-04-18 15:23
I've tryed with jpeg format with no results.
![image](https://cloud.githubusercontent.com/assets/17119871/14609482/49da9204-058a-11e6-8df1-413b0e17cf64.jpg)

**Comment by leandrotoledo** [comment] 2016-04-18 15:37
@gibosler Cool, I'll look into that, meanwhile could you check if you are using the latest stable version?
»> import telegram
»> print telegram.__version__
3.4

**Comment by gibosler** [comment] 2016-04-18 16:26
`
>>> import telegram
>>> print "VERSION: " + str(telegram.__version__)
VERSION: 3.4
`

**Comment by rahiel** [comment] 2016-04-19 17:16
I cannot reproduce this issue on python 2.7 and version 3.4 of the library, your graph is sent properly using `bot.sendPhoto(chat_id=chat_id, photo=open('./bla.jpg', 'rb'))`, could you try `bot.sendPhoto(chat_id=chat_id, photo=open('./bla.jpg', 'r'))`?

**Comment by vadimdne** [comment] 2016-04-20 20:39
Hi, I'm getting exactly the same issue with sendPhoto. Full details are [in this SO question](http://stackoverflow.com/questions/36727763/unicodedecodeerror-when-trying-to-sendphoto-via-python-telegram-bot):

I'm uploading JPG file, both open(file, 'rb') and open(file, 'r') result in same encoding error.

Python 2.7, Telegram 3.4

**Comment by vadimdne** [comment] 2016-04-20 21:05
By the way, the self implemented send_photo method mentioned in #110 works just fine for me.

**Comment by gibosler** [comment] 2016-04-21 06:26
I've made some tests. In many case it works, maybe when i start a python shell, starting bot and sendPhoto. The problem exists when the library is used with others extensions (updater in my case) and/or importing django models. 
Last test i've removed import of os and sys lib in my script and it works. Re-adding this it works too, but when i import logging library and log config it fails. Error is always on unicodedecode error on post data of image. The same error using sendDocument.. 
It seems a randomized error.. i'm investigating on it..

**Comment by leandrotoledo** [comment] 2016-04-23 01:38
Hi @gibosler,

Could you mock up some code so we can also reproduce the problem?

Thanks!

**Comment by slonvpalto** [comment] 2016-04-28 21:54
I can clearly reproduce the issue with a jpeg file. What should I supply to assist you fixing the problem?

**Comment by leandrotoledo** [comment] 2016-04-29 12:19
Hi @slonvpalto could you provide more details about the issue, like:
- Python version you are running on
- python-telegram-bot you are using
- Are you using this library within another library or framework, like Django / Flask / etc?
- Maybe a piece of code?

Thanks!

**Comment by thinkxl** [comment] 2016-05-06 02:37
FYI, I can send pictures without problem like this `bot.sendPhoto(update.message.chat_id, photo='./image_file.jpg')`

**Comment by leandrotoledo** [comment] 2016-05-15 23:43
Friendly ping @slonvpalto @gibosler, any luck on how to reproduce this?

**Comment by grumbler** [comment] 2016-05-16 12:59
The reason for this problem is unicode somewhere. (At least it was in my case)
It could be the leading part of the path.

**Comment by Nanoseb** [comment] 2016-05-22 20:12
I had the same issue and it was solved by changing the encoding of the path to `utf-8`

**Comment by leandrotoledo** [comment] 2016-05-23 22:28
I'm resolving this issue, please feel free to reopen if further attention here is needed. 
Also check @Nanoseb's comment, seems like most of time the path to file needs to be `utf-8` encoded.

**Closed by leandrotoledo** 2016-05-23 22:28 UTC
Labels: pending reply, question
