### ISSUE TITLE
Bot stops responding after network fluctuation

### ISSUE THREAD

**Issue by ritiek** [python-telegram-bot/python-telegram-bot#510] opened 2017-01-29 15:02 UTC
### Steps to reproduce
1. Start the bot as usual and commands sent from telegram work.

2. Reboot the modem (internet goes down) and wait for internet to work again (internet goes up again after some time).

3.  Send some command to the bot.

### Expected behaviour
Commands sent should work after internet goes up again.

### Actual behaviour
Commands won't work after internet is up again and are totally ignored by bot.

### Configuration
**Operating System:**
Raspbian Jessie on Raspberry Pi 2 B

output of `uname -a`:
`Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux`

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 5.3.0
urllib3 1.20
certifi 2017.01.23
future 0.16.0
Python 2.7.9 (default, Sep 17 2016, 20:26:04)  [GCC 4.9.2]

### Logs
2017-01-29 20:10:36,943 - JobQueue - DEBUG - JobQueue thread started
2017-01-29 20:10:36,947 - telegram.ext.updater - DEBUG - dispatcher - started
2017-01-29 20:10:36,953 - telegram.ext.updater - DEBUG - updater - started
2017-01-29 20:10:36,954 - telegram.ext.updater - DEBUG - Updater thread started
2017-01-29 20:10:36,954 - telegram.bot - DEBUG - Entering: setWebhook
2017-01-29 20:10:36,961 - telegram.ext.dispatcher - DEBUG - Dispatcher started
2017-01-29 20:10:43,864 - telegram.bot - DEBUG - True
2017-01-29 20:10:43,865 - telegram.bot - DEBUG - Exiting: setWebhook
2017-01-29 20:10:43,866 - telegram.bot - DEBUG - Entering: getUpdates
2017-01-29 20:10:51,350 - telegram.bot - DEBUG - Getting updates: [642177351]
2017-01-29 20:10:51,352 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x760a5110>]
2017-01-29 20:10:51,353 - telegram.bot - DEBUG - Exiting: getUpdates
2017-01-29 20:10:51,354 - telegram.bot - DEBUG - Entering: getUpdates
2017-01-29 20:10:51,384 - telegram.ext.dispatcher - DEBUG - Processing Update: {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [{'length': 9, 'type': u'bot_command', 'offset': 0}], 'text': u'/snapshot', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': u'Ritiek', 'first_name': u'Ritiek', 'last_name': u'Malhotra', 'type': '', 'id': 329187815}, 'supergroup_chat_created': False, 'chat': {'username': u'Ritiek', 'first_name': u'Ritiek', 'all_members_are_admins': False, 'title': '', 'last_name': u'Malhotra', 'type': u'private', 'id': 329187815}, 'photo': [], 'date': 1485700851, 'group_chat_created': False, 'caption': '', 'message_id': 728, 'new_chat_title': ''}, 'update_id': 642177351}

(i send command now)

2017-01-29 20:10:51,385 - telegram.bot - DEBUG - Entering: sendChatAction
2017-01-29 20:10:53,243 - telegram.bot - DEBUG - True
2017-01-29 20:10:53,244 - telegram.bot - DEBUG - Exiting: sendChatAction
2017-01-29 20:10:53,284 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2017-01-29 20:10:53,290 - requests.packages.urllib3.connectionpool - DEBUG - "GET /0/action/snapshot HTTP/1.1" 200 None
2017-01-29 20:10:53,447 - telegram.bot - DEBUG - Entering: sendPhoto
2017-01-29 20:10:54,752 - telegram.bot - DEBUG - {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [], 'text': '', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': u'PersonalPiBot', 'first_name': u'Raspberry Pi', 'last_name': '', 'type': '', 'id': 285030080}, 'supergroup_chat_created': False, 'chat': {'username': u'Ritiek', 'first_name': u'Ritiek', 'all_members_are_admins': False, 'title': '', 'last_name': u'Malhotra', 'type': u'private', 'id': 329187815}, 'photo': [{'width': 90, 'height': 67, 'file_id': 'AgADBQADsacxG6a0cFTxrx6XSJxhJPdKyjIABF6A6kVR2cpsI-gAAgI', 'file_size': 745}, {'width': 320, 'height': 240, 'file_id': 'AgADBQADsacxG6a0cFTxrx6XSJxhJPdKyjIABALoKINajKI-JOgAAgI', 'file_size': 7484}, {'width': 640, 'height': 480, 'file_id': 'AgADBQADsacxG6a0cFTxrx6XSJxhJPdKyjIABdTFtlGmu00l6AACAg', 'file_size': 15483}], 'date': 1485700854, 'group_chat_created': False, 'caption': '', 'message_id': 729, 'new_chat_title': ''}
2017-01-29 20:10:54,755 - telegram.bot - DEBUG - Exiting: sendPhoto
2017-01-29 20:11:01,803 - telegram.bot - DEBUG - No new updates found.
2017-01-29 20:11:01,804 - telegram.bot - DEBUG - []
2017-01-29 20:11:01,805 - telegram.bot - DEBUG - Exiting: getUpdates
2017-01-29 20:11:01,806 - telegram.bot - DEBUG - Entering: getUpdates

(i reboot my modem here)

2017-01-29 20:11:16,840 - telegram.ext.updater - ERROR - Error while getting Updates: Timed out
2017-01-29 20:11:16,891 - telegram.ext.dispatcher - DEBUG - Processing Update: Timed out
2017-01-29 20:11:17,842 - telegram.bot - DEBUG - Entering: getUpdates
2017-01-29 20:11:37,868 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x760a53d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot285030xxx:xxx2tuY0lzjxwP_FGgNebD9L_Wuc_R0Hipo/getUpdates
2017-01-29 20:11:57,889 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x760a5530>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot285030xxx:xxx2tuY0lzjxwP_FGgNebD9L_Wuc_R0Hipo/getUpdates
2017-01-29 20:12:17,911 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x76085110>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /bot285030xxx:xxx2tuY0lzjxwP_FGgNebD9L_Wuc_R0Hipo/getUpdates
2017-01-29 20:12:31,098 - telegram.bot - DEBUG - No new updates found.
2017-01-29 20:12:31,099 - telegram.bot - DEBUG - []
2017-01-29 20:12:31,100 - telegram.bot - DEBUG - Exiting: getUpdates

(my modem is up again and i send another command now)

2017-01-29 20:12:31,101 - telegram.bot - DEBUG - Entering: getUpdates
2017-01-29 20:12:34,704 - telegram.bot - DEBUG - Getting updates: [642177352]
2017-01-29 20:12:34,706 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x760a57b0>]
2017-01-29 20:12:34,707 - telegram.bot - DEBUG - Exiting: getUpdates
2017-01-29 20:12:34,708 - telegram.bot - DEBUG - Entering: getUpdates
2017-01-29 20:12:34,741 - telegram.ext.dispatcher - DEBUG - Processing Update: {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [], 'entities': [{'length': 9, 'type': u'bot_command', 'offset': 0}], 'text': u'/snapshot', 'migrate_from_chat_id': 0, 'channel_chat_created': False, 'from': {'username': u'Ritiek', 'first_name': u'Ritiek', 'last_name': u'Malhotra', 'type': '', 'id': 329187815}, 'supergroup_chat_created': False, 'chat': {'username': u'Ritiek', 'first_name': u'Ritiek', 'all_members_are_admins': False, 'title': '', 'last_name': u'Malhotra', 'type': u'private', 'id': 329187815}, 'photo': [], 'date': 1485700954, 'group_chat_created': False, 'caption': '', 'message_id': 730, 'new_chat_title': ''}, 'update_id': 642177352}
2017-01-29 20:12:34,742 - telegram.bot - DEBUG - Entering: sendChatAction
2017-01-29 20:12:45,013 - telegram.bot - DEBUG - No new updates found.
2017-01-29 20:12:45,014 - telegram.bot - DEBUG - []
2017-01-29 20:12:45,015 - telegram.bot - DEBUG - Exiting: getUpdates
2017-01-29 20:12:45,016 - telegram.bot - DEBUG - Entering: getUpdates
2017-01-29 20:12:50,452 - telegram.bot - DEBUG - Getting updates: [642177353]
2017-01-29 20:12:50,454 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x76c23d90>]
2017-01-29 20:12:50,455 - telegram.bot - DEBUG - Exiting: getUpdates
2017-01-29 20:12:50,456 - telegram.bot - DEBUG - Entering: getUpdates
2017-01-29 20:13:00,773 - telegram.bot - DEBUG - No new updates found.
2017-01-29 20:13:00,775 - telegram.bot - DEBUG - []
2017-01-29 20:13:00,776 - telegram.bot - DEBUG - Exiting: getUpdates
2017-01-29 20:13:00,777 - telegram.bot - DEBUG - Entering: getUpdates

**Comment by Eldinnie** [comment] 2017-01-30 10:21
First off all, revoke your token (since it's in the log)

**Comment by Ritiek** [comment] 2017-01-30 10:50
@Eldinnie I edited it out, don't worry

**Comment by jh0ker** [comment] 2017-02-27 17:12
it's caused by a bug in urllib3, we're working on a fix on this but it's a complex issue.

**Comment by jh0ker** [comment] 2017-03-09 09:30
@Ritiek If you're still here, can you try installing the latest `master` branch of `python-telegram-bot` and our custom `urllib3` version from `git@github.com:tsnoam/urllib3.git` branch `ptb` to see if it resolves the problem?

**Comment by tsnoam** [comment] 2017-03-09 09:33
@jh0ker @Ritiek 
let me just clarify that this had been a realy dodgy problem because it involves network timeouts which are hard to reproduce. We have something that we found to be working better in some scenarios, but we'd like to get as much feedback as possible before we'll relase a new version.

**Comment by xerxe6** [comment] 2017-03-11 08:30
Such a serious problem. daily bot outage.

**Comment by jh0ker** [comment] 2017-03-11 11:04
@xerxe6 Did you try installing the custom urllib3 version?

**Comment by xerxe6** [comment] 2017-03-13 15:45
@jh0ker Did not resolve the issue.

**Comment by kryksyh** [comment] 2017-04-03 05:58
I have similar problem. Our network structure is somewhat unusual, server which is running bot is behind http proxy and proxy server is in another network connected via VPN.
So VPN\proxy connections are far from stable, and after some fluctuations bot stops responding.

In logs I see that it does get updates:
```
2017-04-03 08:40:59,584 - telegram.bot - DEBUG - Exiting: getUpdates
2017-04-03 08:40:59,584 - telegram.bot - DEBUG - Entering: getUpdates
2017-04-03 08:41:01,134 - telegram.bot - DEBUG - Getting updates: [795682123]
2017-04-03 08:41:01,135 - telegram.bot - DEBUG - [<telegram.update.Update object at 0x3568190>]
```
But dispatcher does not execute any callbacks.

My code is something like this:
```python
    updater = Updater(token='TOKEN_HERE')
    dispatcher = updater.dispatcher

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler('start', start)],
        states={
            STAT_AUTH_REQUIRED: [MessageHandler(Filters.text, auth)],
            STAT_ID_REQUIRED: [MessageHandler(Filters.text, set_urvid)]
        },
        fallbacks=[CommandHandler('cancel', cancel)]
    )
    dispatcher.add_handler(conv_handler)
    dispatcher.add_error_handler(error)
```

**Comment by kryksyh** [comment] 2017-04-04 10:12
@jh0ker I installed your custom urllib3, and it didn't help. I see updates in logs, but dispatcher is silent.

**Comment by vsmelov** [comment] 2017-05-29 09:01
What is a workaround for this bug?
Can i just add
while True:
    try:
        dispatch(...)
    except Something:
        pass

or something like this?
We sometimes have troubles with connection so I can not use this Lib ((

**Comment by jh0ker** [comment] 2017-05-29 09:03
@vsmelov Does the problem persist with version 6.0.1?

**Comment by kryksyh** [comment] 2017-05-29 12:29
Yes, it still happens to me.

**Comment by vsmelov** [comment] 2017-05-30 13:51
@jh0ker 
It still happens to me too.
python-telegram-bot==6.0.3

**Comment by Ritiek** [comment] 2017-05-30 14:43
I am sorry, I totally forgot this issue here. I also tried [telepot](https://github.com/nickoala/telepot) but it seems to work fine for me despite of using urllib3. I am not sure how they do it.

**Comment by tsnoam** [comment] 2017-06-03 12:13
@vsmelov @kryksyh 
We find it very difficult to recreate the issue.
Can you try this test program (in the link below) on the same server where you witness the problem?
Once you've recreated the problem, please send us all the output produced by the test program.

https://gist.github.com/tsnoam/33136241f89b6401f4d4cc1cc1d7865f

**Comment by tsnoam** [comment] 2017-06-03 12:16
@xerxe6 @Ritiek your input will be appreciated too.

**Comment by kryksyh** [comment] 2017-06-03 12:36
Ok, I will send you logs as soon as catch the bug.

**Comment by Ritiek** [comment] 2017-06-03 19:19
@tsnoam That gist does not seem to reply back to my messages (even if my internet does not fluctuate at all). Can you check?

**Comment by tsnoam** [comment] 2017-06-03 19:26
@Ritiek It is supposed to reply to /start

**Comment by Ritiek** [comment] 2017-06-03 20:05
@tsnoam You're right.

So, I have this weird problem in my modem which gives me timeouts if I use `nmap` on some IP address. It helps me generate timeouts on demand. The internet comes back if I reboot my modem.

I'm using the latest pypi release of `python-telegram-bot` as of now by using `pip install -U python telegram-bot` and now the bot seems to correctly reply messages as soon as internet is re-established. This problem is fixed for me!

If you're interested in logs

>pi@raspberrypi:~/scripts/python $ sudo python3 test.py
python-telegram-bot 6.0.3
urllib3 1.21.1
certifi 2017.04.17
future 0.16.0
Python 3.5.3 (default, May  5 2017, 23:07:09)  [GCC 4.9.2]
2017-06-04 01:17:33,698 Setting singleton dispatcher as <telegram.ext.dispatcher.Dispatcher object at 0x76179790>
2017-06-04 01:17:33,703 JobQueue thread started
2017-06-04 01:17:33,707 dispatcher - started
2017-06-04 01:17:33,710 updater - started
2017-06-04 01:17:33,713 Updater thread started
2017-06-04 01:17:33,715 Entering: set_webhook
2017-06-04 01:17:33,723 Dispatcher started
2017-06-04 01:17:33,726 Starting new HTTPS connection (1): api.telegram.org
2017-06-04 01:17:34,819 https://api.telegram.org:443 "POST /*<removed_token>*/setWebhook HTTP/1.1" 200 68
2017-06-04 01:17:34,825 True
2017-06-04 01:17:34,826 Exiting: set_webhook
2017-06-04 01:17:34,828 Entering: get_updates
2017-06-04 01:17:38,940 https://api.telegram.org:443 "POST /*<removed_token>*/getUpdates HTTP/1.1" 200 394
2017-06-04 01:17:38,945 Getting updates: [846584123]
2017-06-04 01:17:38,948 [<telegram.update.Update object at 0x76191d90>]
2017-06-04 01:17:38,962 Exiting: get_updates
2017-06-04 01:17:38,965 Processing Update: {'message': {'new_chat_members': [], 'entities': [{'length': 6, 'offset': 0, 'type': 'bot_command'}], 'text': '/start', 'photo': [], 'new_chat_photo': [], 'group_chat_created': False, 'date': 1496519258, 'supergroup_chat_created': False, 'new_chat_member': None, 'delete_chat_photo': False, 'message_id': 19, 'chat': {'first_name': 'Ritiek', 'type': 'private', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'from': {'language_code': 'en-US', 'first_name': 'Ritiek', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'channel_chat_created': False}, 'update_id': 846584123}
2017-06-04 01:17:38,967 Entering: get_me
2017-06-04 01:17:38,972 Entering: get_updates
2017-06-04 01:17:38,976 Starting new HTTPS connection (2): api.telegram.org
2017-06-04 01:17:39,163 https://api.telegram.org:443 "GET /*<removed_token>*/getMe HTTP/1.1" 200 86
2017-06-04 01:17:39,167 {'first_name': 'TeleRust', 'username': 'TestRustBot', 'id': 341129247}
2017-06-04 01:17:39,169 Exiting: get_me
2017-06-04 01:17:39,171 Entering: send_message
2017-06-04 01:17:39,569 https://api.telegram.org:443 "POST /*<removed_token>*/sendMessage HTTP/1.1" 200 260
2017-06-04 01:17:39,573 {'new_chat_members': [], 'entities': [], 'text': 'Got message', 'photo': [], 'new_chat_photo': [], 'group_chat_created': False, 'date': 1496519259, 'supergroup_chat_created': False, 'new_chat_member': None, 'delete_chat_photo': False, 'message_id': 20, 'chat': {'first_name': 'Ritiek', 'type': 'private', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'from': {'first_name': 'TeleRust', 'username': 'TestRustBot', 'id': 341129247}, 'channel_chat_created': False}
2017-06-04 01:17:39,575 Exiting: send_message
2017-06-04 01:17:50,124 https://api.telegram.org:443 "POST /*<removed_token>*/getUpdates HTTP/1.1" 200 23
2017-06-04 01:17:50,128 No new updates found.
2017-06-04 01:17:50,129 []
2017-06-04 01:17:50,131 Exiting: get_updates
2017-06-04 01:17:50,133 Entering: get_updates
2017-06-04 01:18:00,342 https://api.telegram.org:443 "POST /*<removed_token>*/getUpdates HTTP/1.1" 200 23
2017-06-04 01:18:00,346 No new updates found.
2017-06-04 01:18:00,347 []
2017-06-04 01:18:00,349 Exiting: get_updates
2017-06-04 01:18:00,350 Entering: get_updates
2017-06-04 01:18:10,570 https://api.telegram.org:443 "POST /*<removed_token>*/getUpdates HTTP/1.1" 200 23
2017-06-04 01:18:10,574 No new updates found.
2017-06-04 01:18:10,575 []
2017-06-04 01:18:10,576 Exiting: get_updates
2017-06-04 01:18:10,578 Entering: get_updates
2017-06-04 01:18:20,792 https://api.telegram.org:443 "POST /*<removed_token>*/getUpdates HTTP/1.1" 200 23
2017-06-04 01:18:20,796 No new updates found.
2017-06-04 01:18:20,797 []
2017-06-04 01:18:20,799 Exiting: get_updates
>
>(internet drops here)
>
>2017-06-04 01:18:20,800 Entering: get_updates
2017-06-04 01:18:32,813 Error while getting Updates: Timed out
2017-06-04 01:18:32,814 Processing Update: Timed out
2017-06-04 01:18:33,816 Entering: get_updates
2017-06-04 01:18:33,819 Starting new HTTPS connection (3): api.telegram.org
2017-06-04 01:18:53,842 Incremented Retry for (url='/*<removed_token>*/getUpdates'): Retry(total=2, connect=None, read=None, redirect=None)
2017-06-04 01:18:53,843 Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x76191cf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /*<removed_token>*/getUpdates
2017-06-04 01:18:53,844 Starting new HTTPS connection (4): api.telegram.org
2017-06-04 01:19:13,862 Incremented Retry for (url='/*<removed_token>*/getUpdates'): Retry(total=1, connect=None, read=None, redirect=None)
2017-06-04 01:19:13,864 Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x76191c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /*<removed_token>*/getUpdates
2017-06-04 01:19:13,865 Starting new HTTPS connection (5): api.telegram.org
2017-06-04 01:19:29,923 https://api.telegram.org:443 "POST /*<removed_token>*/getUpdates HTTP/1.1" 200 394
2017-06-04 01:19:29,926 Getting updates: [846584124]
2017-06-04 01:19:29,929 [<telegram.update.Update object at 0x720ec530>]
2017-06-04 01:19:29,930 Exiting: get_updates
2017-06-04 01:19:29,933 Processing Update: {'message': {'new_chat_members': [], 'entities': [{'length': 6, 'offset': 0, 'type': 'bot_command'}], 'text': '/start', 'photo': [], 'new_chat_photo': [], 'group_chat_created': False, 'date': 1496519315, 'supergroup_chat_created': False, 'new_chat_member': None, 'delete_chat_photo': False, 'message_id': 21, 'chat': {'first_name': 'Ritiek', 'type': 'private', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'from': {'language_code': 'en-US', 'first_name': 'Ritiek', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'channel_chat_created': False}, 'update_id': 846584124}
2017-06-04 01:19:29,935 Entering: send_message
2017-06-04 01:19:29,939 Entering: get_updates
2017-06-04 01:19:30,332 https://api.telegram.org:443 "POST /*<removed_token>*/sendMessage HTTP/1.1" 200 260
2017-06-04 01:19:30,336 {'new_chat_members': [], 'entities': [], 'text': 'Got message', 'photo': [], 'new_chat_photo': [], 'group_chat_created': False, 'date': 1496519370, 'supergroup_chat_created': False, 'new_chat_member': None, 'delete_chat_photo': False, 'message_id': 22, 'chat': {'first_name': 'Ritiek', 'type': 'private', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'from': {'first_name': 'TeleRust', 'username': 'TestRustBot', 'id': 341129247}, 'channel_chat_created': False}
2017-06-04 01:19:30,339 Exiting: send_message
2017-06-04 01:19:41,957 Error while getting Updates: Timed out
2017-06-04 01:19:41,958 Processing Update: Timed out
>
>(internet is up again here)
>
>2017-06-04 01:19:42,959 Entering: get_updates
2017-06-04 01:19:42,961 Starting new HTTPS connection (6): api.telegram.org
2017-06-04 01:19:44,034 https://api.telegram.org:443 "POST /*<removed_token>*/getUpdates HTTP/1.1" 200 394
2017-06-04 01:19:44,038 Getting updates: [846584125]
2017-06-04 01:19:44,040 [<telegram.update.Update object at 0x720ec8f0>]
2017-06-04 01:19:44,042 Exiting: get_updates
2017-06-04 01:19:44,045 Processing Update: {'message': {'new_chat_members': [], 'entities': [{'length': 6, 'offset': 0, 'type': 'bot_command'}], 'text': '/start', 'photo': [], 'new_chat_photo': [], 'group_chat_created': False, 'date': 1496519383, 'supergroup_chat_created': False, 'new_chat_member': None, 'delete_chat_photo': False, 'message_id': 23, 'chat': {'first_name': 'Ritiek', 'type': 'private', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'from': {'language_code': 'en-US', 'first_name': 'Ritiek', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'channel_chat_created': False}, 'update_id': 846584125}
2017-06-04 01:19:44,046 Entering: send_message
2017-06-04 01:19:44,051 Entering: get_updates
2017-06-04 01:19:44,444 https://api.telegram.org:443 "POST /*<removed_token>*/sendMessage HTTP/1.1" 200 260
2017-06-04 01:19:44,448 {'new_chat_members': [], 'entities': [], 'text': 'Got message', 'photo': [], 'new_chat_photo': [], 'group_chat_created': False, 'date': 1496519384, 'supergroup_chat_created': False, 'new_chat_member': None, 'delete_chat_photo': False, 'message_id': 24, 'chat': {'first_name': 'Ritiek', 'type': 'private', 'username': '*<removed_usename>*', 'id': *<removed_id>*, 'last_name': 'Malhotra'}, 'from': {'first_name': 'TeleRust', 'username': 'TestRustBot', 'id': 341129247}, 'channel_chat_created': False}
2017-06-04 01:19:44,450 Exiting: send_message
2017-06-04 01:19:54,250 https://api.telegram.org:443 "POST /*<removed_token>*/getUpdates HTTP/1.1" 200 23
2017-06-04 01:19:54,254 No new updates found.
2017-06-04 01:19:54,255 []
2017-06-04 01:19:54,257 Exiting: get_updates
2017-06-04 01:19:54,258 Entering: get_updates

Thanks a lot!

**Comment by tsnoam** [comment] 2017-06-07 20:26
Sorry for my delay in response. Had a few busy days.

@Ritiek - Thanks for the response, I'm happy to hear that things are fixed for you.

@kryksyh - I've just noticed you've asked about urllib3. With the latest ptb we bundle our forked version of urllib3 so you shouldn't worry about its version. Have you had any progress with recreating the issue?

**Comment by kryksyh** [comment] 2017-06-08 09:08
@tsnoam your test script is working fine since I started it for almost a week now. I think it is something wrong with my code in message handlers that is causing dispatcher to hang.

**Comment by tsnoam** [comment] 2017-06-09 14:53
@kryksyh - Thanks for the update.
@vsmelov @xerxe6 - can you confirm that the issue is resolved you as well? If not, can you please try the test script and send the logs to us?

**Comment by vsmelov** [comment] 2017-06-09 14:55
Yes, this problem solved for me, thnx

9 июня 2017 г. 5:53 PM пользователь "Noam Meltzer" <notifications@github.com>
написал:

**Comment by kryksyh** [comment] 2017-06-13 06:06
Yes, it was definitely fault in my code. Now as it is fixed everything works fine and rock-stable, at least on the library side. Thank you!

**Comment by tsnoam** [comment] 2017-06-22 21:56
Ok, so everyone on this issue had responded that they do not witness the problem any more or that it was an issue with their code.
That is except for @xerxe6 who haven't responded at all.
Due to the above I'm feeling confident closing this issue.

**Closed by tsnoam** 2017-06-22 21:56 UTC
Labels: bug, pending reply
