### ISSUE TITLE
Sending message whit reply_markup to group (results force_reply!)

### ISSUE THREAD

**Issue by alistvt** [python-telegram-bot/python-telegram-bot#1329] opened 2019-01-23 17:28 UTC
### Expected behaviour
I want to send a message with a `reply_markup ` keyboard to a group.
and I don't want it to be `force_reply`

### Actual behaviour
It gets `force_reply`

### Configuration
**Operating System:** 
Ubuntu 16.04

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 11.1.0
certifi 2018.11.29
future 0.17.1
Python 3.6.7 

### Codes I have tried
```
#cv.py
B_Button = 'button'
Q_Answer = 'answer'

```
```

        if update.message.text == '1':
		bot.send_message(update.message.chat_id, 
			text=cv.Q_Answer, 
			reply_markup=ReplyKeyboardMarkup(
				keyboard=[[cv.B_Button]], 
				resize_keyboard = True, 
				force_reply=False))
	elif update.message.text == 'r':
		bot.send_message(update.message.chat_id, 
			text=cv.Q_Answer, 
			reply_markup=ReplyKeyboardRemove())
	elif update.message.text == '2':
		bot.send_message(update.message.chat_id, 
			text=cv.Q_Answer, 
			reply_markup=ForceReply(
				keyboard=[[cv.B_Button]], 
				resize_keyboard = True))
	elif update.message.text == '3':
		bot.send_message(update.message.chat_id, 
			text=cv.Q_Answer, 
			reply_markup=ReplyKeyboardMarkup(
				keyboard=[[cv.B_Button]], 
				resize_keyboard = True, 
				force_reply=True))
	elif update.message.text == '4':
		bot.send_message(update.message.chat_id, 
			text=cv.Q_Answer, 
			reply_markup=ForceReply(
				keyboard=[[cv.B_Button]], 
				force_reply=False))
	elif update.message.text == '5':
		bot.send_message(update.message.chat_id, 
			text=cv.Q_Answer, 
			reply_markup=ForceReply(
				keyboard=[[cv.B_Button]], 
				force_reply=True))
	elif update.message.text == '6':
		bot.send_message(update.message.chat_id, 
			text=cv.Q_Answer, 
			reply_markup=ReplyKeyboardMarkup(
				keyboard=[[cv.B_Button]], 
				resize_keyboard = True), 
				force_reply=False)
```

thanks for helping. 🙇‍♂️

**Comment by alistvt** [comment] 2019-01-23 18:46
The problem solved finally : |
This happens only in telegram desktop!

**Comment by jsmnbom** [comment] 2019-01-30 19:05
`ReplyKeyboardMarkup` has no `force_reply` argument at all. A `ReplyKeyboardMarkup` always pops up a keyboard that the user can then choose to hide if they desire. This is not something we can change since it's just how telegram clients work.
Closing as this is not a bug.

**Closed by jsmnbom** 2019-01-30 19:05 UTC
