### ISSUE TITLE
[QUESTION] raise InvalidToken()telegram.error.InvalidToken: Invalid token

### ISSUE THREAD

**Issue by RenatohRibeiro** [python-telegram-bot/python-telegram-bot#2474] opened 2021-04-17 02:44 UTC
I'm using a local bot api running with --local, but I can't download anything

### Steps to reproduce
1. Use self-host bot api, with --local.

2.   Get any file via 
 ```
image_file = context.bot.get_file(file_id)
image_file.download(imagename) 
```
from telegram server. (Sent by user in my case.)

### Expected behaviour
It was supposed to download the media, which in this case is a photo

### Actual behaviour
The API simply cannot download the media

### Configuration
**Operating System:**
Ubuntu 20.04.2 LTS
Python 3.8
**Version of Python, python-telegram-bot & dependencies:**
PTB 13.4.1

### Logs
```python
2021-04-17 02:34:35,754 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):                                                          
File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/utils/promise.py", line 79, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
File "/home/ubuntu/SmudgePTB13/smudge/modules/searchimage.py", line 60, in reverse
    image_file.download(imagename)
File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/files/file.py", line 159, in download
    buf = self.bot.request.retrieve(url, timeout=timeout)                                   
File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 373, in retrieve                                                                               
    return self._request_wrapper('GET', url, **urlopen_kwargs)                              
File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 274, in _request_wrapper
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```

**Comment by Bibo-Joshi** [comment] 2021-04-17 07:15
Hi. As pointed out [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Local-Bot-API-Server#working-with-files) (last bullet point), the files are not automatically served and you'll have to set something up yourself for them to be. How exactly that can be done is beyond the scope of PTB, though …

**Comment by nuriddinislamov** [comment] 2021-04-17 13:35
### Regarding your traceback:

Maybe you get a _**valid** **Token**_ from [BotFather](https://t.me/BotFather) then paste it in the Updater?

Check out [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-Your-first-Bot) how that works.

### File issue
For downloading your file, you will need to look up some [python docs](https://docs.python.org/3/library/functions.html?highlight=open#open)

**Comment by RenatohRibeiro** [comment] 2021-04-17 14:45
> Hi. As pointed out [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Local-Bot-API-Server#working-with-files) (last bullet point), the files are not automatically served and you'll have to set something up yourself for them to be. How exactly that can be done is beyond the scope of PTB, though …

But I started BotAPI with --local.

**Comment by RenatohRibeiro** [comment] 2021-04-17 14:46
> ### Regarding your traceback:
> Maybe you get a _**valid** **Token**_ from [BotFather](https://t.me/BotFather) then paste it in the Updater?
> 
> Check out [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-%E2%80%93-Your-first-Bot) how that works.
> 
> ### File issue
> For downloading your file, you will need to look up some [python docs](https://docs.python.org/3/library/functions.html?highlight=open#open)

My token is correct, I can do other things, I just can't download a media.

**Comment by Bibo-Joshi** [comment] 2021-04-17 17:08
> But I started BotAPI with --local.

Ah. Sorry for misreading. I can't reproduce, then. Could you please try the following:

In `/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py`, in the line before 274 insert `print(message)`, so that we can see the exact error message from TG.

**Comment by RenatohRibeiro** [comment] 2021-04-17 17:54
there were no changes, it was the same error

```
2021-04-17 17:53:59,003 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/utils/promise.py", line 79, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/ubuntu/SmudgePTB13-Teste/smudge/modules/searchimage.py", line 60, in reverse    image_file.download(imagename)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/files/file.py", line 159, in download
    buf = self.bot.request.retrieve(url, timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 374, in retrieve
    return self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 274, in _request_wrapper
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```

**Comment by Bibo-Joshi** [comment] 2021-04-17 17:56
So does it print anything at all? can you check `if message is None` or `message == ''` or something like that? Maybe print `print('here is the message:', repr(message))`?
Also can you print out `image_file.file_path` and check if that actually exists?

**Comment by RenatohRibeiro** [comment] 2021-04-17 18:00
This is the code
```
def reverse(update: Update, context: CallbackContext):
    args = context.args
    if os.path.isfile("okgoogle.png"):
        os.remove("okgoogle.png")

    msg = update.effective_message
    chat_id = update.effective_chat.id
    rtmid = msg.message_id
    chat = update.effective_chat
    imagename = "okgoogle.png"

    reply = msg.reply_to_message
    if reply:
        if reply.sticker:
            file_id = reply.sticker.file_id
        elif reply.photo:
            file_id = reply.photo[-1].file_id
        elif reply.document:
            file_id = reply.document.file_id
        else:
            msg.reply_text("Reply to an image or sticker to lookup.")
            return
        image_file = context.bot.get_file(file_id)
        image_file.download(imagename)
        if args:
            txt = args[0]
            try:
                lim = int(txt)
            except:
                lim = 2
        else:
            lim = 2
    elif args and not reply:
        splatargs = msg.text.split(" ")
        if len(splatargs) == 3:
            img_link = splatargs[1]
            try:
                lim = int(splatargs[2])
            except:
                lim = 2
        elif len(splatargs) == 2:
            img_link = splatargs[1]
            lim = 2
        else:
            msg.reply_text("/reverse <link> <amount of images to return.>")
            return
        try:
            urllib.request.urlretrieve(img_link, imagename)
        except HTTPError as HE:
            if HE.reason == 'Not Found':
                msg.reply_text("Image not found.")
                return
            if HE.reason == 'Forbidden':
                msg.reply_text(
                    "Couldn't access the provided link, The website might have blocked accessing to the website by bot or the website does not existed.")
                return
        except URLError as UE:
            msg.reply_text(f"{UE.reason}")
            return
        except ValueError as VE:
            msg.reply_text(
                f"{VE}\nPlease try again using http or https protocol.")
            return
    else:
        msg.reply_text(tld(chat.id, "searchimage_noargs"))
        return

    try:
        searchUrl = 'https://www.google.com/searchbyimage/upload'
        multipart = {'encoded_image': (imagename, open(
            imagename, 'rb')), 'image_content': ''}
        response = requests.post(
            searchUrl, files=multipart, allow_redirects=False)
        fetchUrl = response.headers['Location']

        if response != 400:
            xx = context.bot.send_message(chat_id, "Image was successfully uploaded to Google."
                                  "\nParsing it, please wait.", reply_to_message_id=rtmid)
        else:
            xx = context.bot.send_message(
                chat_id, "Google told me to go away.", reply_to_message_id=rtmid)
            return

        os.remove(imagename)
        match = ParseSauce(fetchUrl + "&hl=en")
        guess = match['best_guess']
        if match['override'] and not match['override'] == '':
            imgspage = match['override']
        else:
            imgspage = match['similar_images']

        if guess and imgspage:
            xx.edit_text(tld(chat.id, "searchimage_processing").format(
                guess, fetchUrl), parse_mode='Markdown', disable_web_page_preview=True)
        else:
            xx.edit_text(tld(chat.id, "searchimage_coundt_anything"))
            return

        images = scam(imgspage, lim)
        if len(images) == 0:
            xx.edit_text(tld(chat.id, "searchimage_noimage").format(
                guess, fetchUrl, imgspage), parse_mode='Markdown', disable_web_page_preview=True)
            return

        imglinks = []
        for link in images:
            lmao = InputMediaPhoto(media=str(link))
            imglinks.append(lmao)

        context.bot.send_media_group(chat_id=chat_id, media=imglinks,
                             reply_to_message_id=rtmid)
        xx.edit_text(tld(chat.id, "searchimage").format(
            guess, fetchUrl, imgspage), parse_mode='Markdown', disable_web_page_preview=True)
    except TelegramError as e:
        print(e)
    except Exception as exception:
        print(exception)

```

**Comment by Bibo-Joshi** [comment] 2021-04-17 18:03
That's nice, but it doesn't really help me with helping you find the issue 😉

**Comment by RenatohRibeiro** [comment] 2021-04-17 18:05
> Então, ele imprime alguma coisa? você pode verificar `if message is None`ou `message == ''`ou algo parecido? Talvez imprimir `print('here is the message:', repr(message))`?
> Você também pode imprimir `image_file.file_path`e verificar se isso realmente existe?

Sorry, I didn't quite understand you want me to look at this in the directory you said before (/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py)?

**Comment by Bibo-Joshi** [comment] 2021-04-17 18:08
1. In that file put `print('here is the message:', repr(message))` before line 274. Then please repot what exactly that prints out.
2. just before your `image_file.download(…)` call, insert a `print('this is the file path:', image_file.file_path)`. Then please report what exactly that prints out and also check if that file actually exists on your machine.

**Comment by RenatohRibeiro** [comment] 2021-04-17 18:31
Uow, problem found apparently has two bars in the directory
*I censored my bot token*
```
this is the file path: https://api.telegram.org/file/botMYBOTTOKEN//home/ubuntu/botapi/MYBOTTOKEN/photos/file_2.jpg
here is the message: 'Not Found'
2021-04-17 18:27:52,736 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/utils/promise.py", line 79, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/ubuntu/SmudgePTB13-Teste/smudge/modules/searchimage.py", line 61, in reverse    image_file.download(imagename)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/files/file.py", line 159, in download
    buf = self.bot.request.retrieve(url, timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 375, in retrieve
    return self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 275, in _request_wrapper
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```

**Comment by Bibo-Joshi** [comment] 2021-04-17 18:38
Okay. So PTB can not guess that `/home/ubuntu/botapi/MYBOTTOKEN/photos/file_2.jpg` is an actual file on your machine an therefore prepends `https://api.telegram.org/file/botMYBOTTOKEN/`. The result is obviously no file on your machine.

* Did you pass anything to the `base_file_url` parameter of PTB?
* Which PTB version are you on? See [here](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-Asked-Questions#how-can-i-check-the-version-of-ptb-i-am-using)

**Comment by RenatohRibeiro** [comment] 2021-04-17 18:41
Yes, the file is present on the machine and I am using PTB 13.4.1

**Comment by Bibo-Joshi** [comment] 2021-04-17 18:45
Then please open the file `/home/ubuntu/.local/lib/python3.8/site-packages/telegram/bot.py` and insert

`print('TG reported the file path', result.get('file_path'), 'and is this a file?', is_local_file(result.get('file_path')))`

before line 2242:

https://github.com/python-telegram-bot/python-telegram-bot/blob/b63877b1f22a85430cadba2ca5bac13e4538eab2/telegram/bot.py#L2240-L2247

**Comment by RenatohRibeiro** [comment] 2021-04-17 18:56
```
TG reported the file path /home/ubuntu/botapi/MYTOKEN/photos/file_6.jpg and is this a file? False
this is the file path: https://api.telegram.org/file/botMYTOKEN//home/ubuntu/botapi/MYTOKEN/photos/file_6.jpg
here is the message: 'Not Found'
2021-04-17 18:55:13,781 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/utils/promise.py", line 79, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/ubuntu/SmudgePTB13-Teste/smudge/modules/searchimage.py", line 61, in reverse    image_file.download(imagename)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/files/file.py", line 159, in download
    buf = self.bot.request.retrieve(url, timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 375, in retrieve
    return self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 275, in _request_wrapper
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```

**Comment by Bibo-Joshi** [comment] 2021-04-17 19:02
Okay. So `is_local_file` can not correctly determine that `/home/ubuntu/botapi/MYTOKEN/photos/file_6.jpg` exists on your system. That function basically does this:

```python
from pathlib import Path

path = Path('/home/ubuntu/botapi/MYTOKEN/photos/file_6.jpg')
print('is path a valid local file?', path.is_file())
```
Please run this (after inserting your token, ofc). 

* If this gives `is path a valid local file? False`, then either TG reports a wrong file name or somethings wrong with pathlib.
* If this gives `is path a valid local file? True`, then something is completly wrong

**Comment by RenatohRibeiro** [comment] 2021-04-17 19:14
Returned "is path a valid local file? True"

**Comment by Bibo-Joshi** [comment] 2021-04-17 19:23
Okay, no this is messed up, but it also narrows down where the error is: in `is_local_file`. The exact code of the fucntion is (see [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/b63877b1f22a85430cadba2ca5bac13e4538eab2/telegram/utils/helpers.py#L79-L93)):

```python
from pathlib import Path

def is_local_file(obj):
    if obj is None:
        return False

    path = Path(obj)
    try:
        return path.is_file()
    except Exception:
        return False
```

and should be located on your system at `/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/helpers.py` starting in line 79. Can you please try to find out where `False` is returned within that function? Because according to [this](https://github.com/python-telegram-bot/python-telegram-bot/issues/2474#issuecomment-821870760), that's what happening …

**Comment by harshil21** [comment] 2021-04-17 20:36
[From the pathlib docs](https://docs.python.org/3/library/pathlib.html#methods): "From py 3.8 onwards, `is_file()` now returns `False` instead of raising an exception for paths that contain characters unrepresentable at the OS level."

Maybe this is what's happening? Other errors like permission denied errors return `False` too.

**Comment by Bibo-Joshi** [comment] 2021-04-17 20:37
@harshil21 But it returns `True`: https://github.com/python-telegram-bot/python-telegram-bot/issues/2474#issuecomment-821873266

**Comment by RenatohRibeiro** [comment] 2021-04-17 22:53
> Okay, now this is messed up, but it also narrows down where the error is: in `is_local_file`. The exact code of the fucntion is (see [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/b63877b1f22a85430cadba2ca5bac13e4538eab2/telegram/utils/helpers.py#L79-L93)):
> 
> ```python
> from pathlib import Path
> 
> def is_local_file(obj):
>     if obj is None:
>         return False
> 
>     path = Path(obj)
>     try:
>         return path.is_file()
>     except Exception:
>         return False
> ```
> 
> and should be located on your system at `/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/helpers.py` starting in line 79. Can you please try to find out where `False` is returned within that function? Because according to [this](https://github.com/python-telegram-bot/python-telegram-bot/issues/2474#issuecomment-821870760), that's what happening …

I'm really lost in that I found out for ** False ** is being returned.

**Comment by Bibo-Joshi** [comment] 2021-04-18 07:36
Sorry, I don't understand you. If you're having troubles finding out, where `False` is returned, do the follownig: In `/home/ubuntu/.local/lib/python3.8/site-packages/telegram/utils/helpers.py` change the `is_local_file` function such that it looks like this:

```python
    if obj is None:
        print('is_local_file returning False, because obj is None')
        return False

    path = Path(obj)
    try:
        print('is_local_file returning',  path.is_file(), ' as output of path.is_file()')
        return path.is_file()
    except Exception:
        print('is_local_file returning False, because of Exception')
        return False
```
Then run your bot. If you get `'is_local_file returning False as output of path.is_file()'`, then there's maybe something wrong with your file permissions, because `path.is_file()` gives `True`, when you run it manually https://github.com/python-telegram-bot/python-telegram-bot/issues/2474#issuecomment-821873266

**Comment by RenatohRibeiro** [comment] 2021-04-18 18:35
is_local_file returning False  as output of path.is_file()

is, the code returned this

**Comment by Bibo-Joshi** [comment] 2021-04-18 21:54
Citing the docs of [`is_file`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.is_file): 

> False is also returned if the path doesn’t exist or is a broken symlink; other errors (such as permission errors) are propagated.

As `False` is apparently only returned from within your bot script and not when you call `Path.is_file` manually, permissions errors would be my bet. In any case it seems like a problem of your setup and not like a bug in PTB. Double check that your bot script can read the files stored. Other than that I fear we can't help you anymore here.

Closing.

**Closed by Bibo-Joshi** 2021-04-18 21:54 UTC
Labels: question
