### ISSUE TITLE
TimedOut on get_updates

### ISSUE THREAD

**Issue by levzhazeschi** [python-telegram-bot/python-telegram-bot#802] opened 2017-08-16 11:21 UTC
Calling get_updates consistently crashes the bot with `telegram.error.TimedOut: Timed out` .

The code:

    updates = self.bot.get_updates(
        offset=self.update_id,
        timeout=30,
        network_delay=1.0
    )

The log:

    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
        six.raise_from(e, None)
      File "<string>", line 2, in raise_from
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
        httplib_response = conn.getresponse()
      File "/app/.heroku/python/lib/python3.6/http/client.py", line 1331, in getresponse
        response.begin()
      File "/app/.heroku/python/lib/python3.6/http/client.py", line 297, in begin
        version, status, reason = self._read_status()
      File "/app/.heroku/python/lib/python3.6/http/client.py", line 258, in _read_status
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
      File "/app/.heroku/python/lib/python3.6/socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "/app/.heroku/python/lib/python3.6/ssl.py", line 1002, in recv_into
        return self.read(nbytes, buffer)
      File "/app/.heroku/python/lib/python3.6/ssl.py", line 865, in read
        return self._sslobj.read(len, buffer)
      File "/app/.heroku/python/lib/python3.6/ssl.py", line 625, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 174, in _request_wrapper
        resp = self._con_pool.request(*args, **kwargs)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
        **urlopen_kw)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
        return self.urlopen(method, url, **extra_kw)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
        response = conn.urlopen(method, u.request_uri, **kw)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
        raise value
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
        chunked=chunked)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
        exc_cls=ReadTimeoutError)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
        raise exc_cls(*args)
    telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=31.0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/app/myapp/bot.py", line 81, in update_forever
        network_delay=1.0
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/bot.py", line 52, in decorator
        result = func(self, *args, **kwargs)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/bot.py", line 1392, in get_updates
        result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 252, in post
        **urlopen_kwargs)
      File "/app/.heroku/python/lib/python3.6/site-packages/telegram/utils/request.py", line 176, in _request_wrapper
        raise TimedOut()
    telegram.error.TimedOut: Timed out

**Comment by mendiej** [comment] 2017-08-18 09:29
I encounter the same issue/error (socket.timeout). For getUpdates, _timeout_ set to anything but 0 results in errors. They are way less frequent when leaving out the _timeout_ parameter, but they still do occur.

**Comment by GladiatorTele** [comment] 2017-08-18 12:31
Encountered same thing yesterday.

**Comment by jh0ker** [comment] 2017-09-21 19:12
FYI the `network_delay` parameter is deprecated (at least in the latest version), so instead you should be using the `read_latency` parameter. And perhaps choosing a higher value for this parameter could solve your issue?

**Comment by Andreychik32** [comment] 2017-10-08 12:35
I have the same issue. Changing the ```read_latency``` parameter seems to not do any work on this issue.

**Comment by tsnoam** [comment] 2017-10-11 20:16
Hi,
I'm sorry for my very late response. 
@levzhazeschi - the problem with long polling is that you might lose connection without the application even knowing it. 
In order to debug network problems we must have much more data. The first things to check (but upon adding the data, more questions will probably rise):
1. Where do you host your bot? I see "heroku", but what region?
2. Followup to 1 - have you measured the latency towards api.telegram.org ?
3. Do you get the error you described immediately at the first `get_updates` attempt or after several successful iterations? 
4. If after several iterations:
4.1. How many iterations until failure?
4.2 How long before failure?
5. To answer 4, and in general, please enable debug logging from ptb and upload logs with more context - before and after the failure.

**Comment by pavel64-sutyrin** [comment] 2017-12-16 17:04
Hey folks! 

I've very affected by this. Is there a quickfix to just ignore these and silently reconnect, if needed?

Are patches welcome, eh? ;)

**Comment by Shadowigor** [comment] 2018-01-23 18:56
Is there any progress on this? I can still reproduce this with the newest version, I start getting the errors after about 30 minutes of inactivity.

**Comment by sobolevn** [comment] 2018-02-08 18:02
I also have this error.

**Comment by Logerfo** [comment] 2018-02-08 18:18
I had this issue using heroku. The problem was that my Procfile started with `web`. I changed it to `bot` and worked like a charm!

**Comment by tsnoam** [comment] 2018-02-18 14:03
Hi,
Please see the recently uploaded wiki article about network errors:
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors

I hope it will answer why a timeout is (unfortunately) an unavoidable condition and will give you some hints on how to fine tune your bot.

In addition, once PR #1007 will be merged, there will be a better handling of timeouts during get_updates (that merge should happen today).

**Closed by tsnoam** 2018-02-18 14:03 UTC
Labels: pending reply

**Comment by yongman** [comment] 2018-04-29 10:30
I also have this problem.

**Comment by Andreychik32** [comment] 2018-04-29 10:32
@yongman, just update python-telegram-bot using this command:
```
pip install -U python-telegram-bot
```

**Comment by yongman** [comment] 2018-04-29 10:41
@Andreychik32 ,Thanks for you reply.

 I update the python-telegram-bot by pip3, but I also get the following errors.

```
2018-04-29 06:37:47,954 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:87)
     Initializing master blueset.telegram...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=9)

During handling of the above exception, another exception occurred:
```
and the bot exit.

By the way, the network from my vps to `api.telegram.org:443` seems good.

**Comment by yongman** [comment] 2018-04-29 10:48
More to say, this error occur from today and bot cannot work as before.

**Comment by Brawl345** [comment] 2018-04-29 10:49
Telegram currently has a power outage: https://twitter.com/telegram/status/990474364108894209

**Comment by yongman** [comment] 2018-04-29 10:55
@Brawl345 Thanks for your information.

It seems the telegram's problem, but the python-telegram-bot also have the bug if timeout exists?

**Comment by tsnoam** [comment] 2018-04-29 18:26
@yongman 
I invite you to join our users group where we have a vibrant community helping each other: https://telegram.me/pythontelegrambotgroup

As suggested in one of the earlier comments please make sure to read the wiki page: https://telegram.me/pythontelegrambotgroup

If you've identified an actual bug with the library please open a new issue instead of reviving an old one.

**Comment by tsnoam** [comment] 2018-04-29 18:28
@yongman 
Sorry, the proper link for the wiki article:
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Handling-network-errors
