### ISSUE TITLE
[QUESTION] sendMediaGroup: when "media" is url, "performer" and "title" keys don't work

### ISSUE THREAD

**Issue by mrtnvgr** [python-telegram-bot/python-telegram-bot#3321] opened 2022-10-31 04:40 UTC
### Issue I am facing

I need to use urls like these:

https://psv4.vkuseraudio.net/s/v1/amp2/SPXTrtBFg_FOVFdqeOacnQu2To3jmCeiT7zYUF9igDj0gvXT3_QsgdP09pn_TRGU5_VA3D9Lco5N1eslabWHck0E6lSakNU-SGlZOqsuCoqS06iO4dXlEwAFrjcbk-uYxK1GVc-zYgo7-6eN94V6GzQawcErjcxp1wtk.mp3

https://cs9-5v4.vkuseraudio.net/s/v1/acmp/Qxy1WPC6d0wQG7Wuu4kmN4Pp0CW6xDxmy0lj7nD_Gb2tJAwO0wxWgxD-xjLU_8yHmb5tPUZvlEYKHCQLanWqyVlvcy4-lFJYQE3BcDHxwIkG02oRsikWNhb23mgW7O7aQfV83Uv7GEL_aJfbJLVUejLILFCu2n70450cju_UcKand4bbCg.mp3

Telegram ignores my title and performer keys and uploads audio under a random name.
Api response:
```
[{'message_id': 8013, 'from': {...}, 'chat': {...}, 'date': 1667190437, 'media_group_id': '13337523503364634', 'audio': {'duration': 274, 'file_name': 'UQrdWwRNTAMWebodwKGz6...NanMdqcD91H.mp3', 'mime_type': 'audio/mpeg', 'file_id': 'CQACAgQAAxkDAAI...ayeKgQ', 'file_unique_id': 'AgADrAMAAjuS_VI', 'file_size': 10962068}}, ...]
```

### Operating System

Linux

### Version of Python, python-telegram-bot & dependencies

```shell
python 3.10.8
```

**Comment by Poolitzer** [comment] 2022-10-31 07:08
Hi.

First of all, do include the code you used to reproduce the error in your Github issue. If the bug was an encoding issue for example because you used some fancy characters in your title/performer string, I would not have been able to catch that.

Secondly, file_name != title. Title is its own optional audio attribute, as you can see here: https://docs.python-telegram-bot.org/en/v20.0a4/telegram.audio.html

Thirdly, I was able to reproduce your issue both in `send_media_group `and `send_audio`, in PTB at first and then I tried out calling the API directly in your browser (If you can spare the time, you could also do this the next time, then you can potentially see if its a bug on our end or on Telegrams and might not even have to open an issue here).

If you pass an URL, the title/performer gets ignored; if you pass a file object (`open("audio.mp3", "rb")`) however, they are correctly attributed.

I imagine that the reason behind is is the same as in https://github.com/tdlib/telegram-bot-api/issues/301#issuecomment-1195582012: From my understanding the bot API does not handle file URLs, it passes it to the telegram servers. They then get the file as is from the source and do not change attributes.

So you could complain about this in the bot-api repo, I don't imagine they will change the server+mtproto API for this, but at least they could clear this up in the bot docs if you ask me.

Anyway, not our issue, so closing.

**Closed by Poolitzer** 2022-10-31 07:08 UTC
Labels: question
