### ISSUE TITLE
Conversation Handler 'None state' isn't executable

### ISSUE THREAD

**Issue by owneroxxor** [python-telegram-bot/python-telegram-bot#1197] opened 2018-08-29 21:51 UTC
**Expected behaviour**
Bot should execute None state handlers when conversation handler asks for it (??) (when the bot rebooted in the server and someone got stuck in a conversation handler state, it forgets that state and asks for None state when receiving msg/callback_queries from that stuck user).
![image](https://user-images.githubusercontent.com/30055123/44817688-92ce6000-abbc-11e8-8a3b-29ac515cfd56.png)

**Actual behaviour**
It doesn't execute any of the None state handlers.

**Steps to reproduce**
```
updater.dispatcher.add_handler(ConversationHandler(entry_points=[CommandHandler('start', start, filters=Filters.private, pass_user_data=True)],
states = {	
		None: [
				CallbackQueryHandler(groupJoinCheck, pattern='^\d+$', pass_user_data=True),
                                MessageHandler(Filters.private, restartBot,  pass_user_data=True)
			],
		GROUP_JOIN_CHECK: [CallbackQueryHandler(groupJoinCheck, pattern='^\d+$', pass_user_data=True)],
		BOT_CHECK :[MessageHandler(Filters.private, botCheck,  pass_user_data=True)],
		EMAIL :[MessageHandler(Filters.private, getEmail, pass_user_data=True)],
		CONFIRM_EMAIL :[MessageHandler(Filters.private, confirmEmail, pass_user_data=True)]
		},
	fallbacks = [RegexHandler('(?i)^\/?Cancel', cancel)],
	allow_reentry =True
	)
)
```

**Comment by jsmnbom** [comment] 2018-09-01 17:41
I could be wrong. But I think currently that having None as the state is the same as not having a state.. Therefore the Handlers that you want to use on a None state, should probably be in your entry_points... I think :)

**Comment by tsnoam** [comment] 2018-09-10 12:05
I'm with @jsmnbom here. Closing as not a bug.

**Closed by tsnoam** 2018-09-10 12:05 UTC
Labels: pending reply
