### ISSUE TITLE
Add stop propagation logic

### ISSUE THREAD

**Issue by s-chizhik** [python-telegram-bot/python-telegram-bot#666] opened 2017-06-13 07:52 UTC
Hi! I see that `dispatcher` can take handlers to different groups:

```python
for group in self.groups:
    for handler in self.handlers[group]:
        try:
            if handler.check_update(update):
                handler.handle_update(update, self)
                break
        # Dispatch any errors
        except TelegramError as te:

```

Such realization doesn't allow us to cleanly stop handling from a group with a lower number. How do you think about some logic, which will make it? Ex, action handler can raise some exception, like `StopPropagationExeption`:
```python
def custom_handler(bot: Bot, update: Update):
    # handling stuff...
    raise StopPropagationException # or maybe wrap it to bot.updater.stop_propagation()

dispatcher.add(custom_handler)
```

```python
for group in self.groups:
    for handler in self.handlers[group]:
        try:
            if handler.check_update(update):
                handler.handle_update(update, self)
                break
        # Dispatch any errors
        except TelegramError as te:
    except StopPropagationExeption:
        pass
```

I've just noticed, that group mechanism allows us to create something like middleware, to handle such things as authorization or smth else. I suppose this logic would be useful.

**Comment by jh0ker** [comment] 2017-06-13 08:19
Hello,
This is indeed a duplicate of #559, but I didn't answer it on github yet, so:

Yes, adding an Exception like you proposed would be a very straightforward way to solve this. However, it has one issue: The return value of callbacks is used by the `ConversationHandler` to determine the new state. So, you couldn't have both, obviously. Perhaps this is not much of a problem, because you wouldn't want to use the two in combination. 
Using a method like `bot.dispatcher.stop_propagation()` would be an option, but it would be a bit strange, especially since there is no real reason for `Bot` to have a reference to `Dispatcher`. What do you think?

**Comment by s-chizhik** [comment] 2017-06-13 13:42
> This is indeed a duplicate of #559

Oh, I see it. Just haven't noticed that issue :(

> Yes, adding an Exception like you proposed would be a very straightforward way to solve this. However, it has one issue: The return value of callbacks is used by the ConversationHandler to determine the new state. So, you couldn't have both, obviously. Perhaps this is not much of a problem, because you wouldn't want to use the two in combination.

Probably you are right. I guess exception is better than return value. In case when user need to change a state of `ConversationHandler` – exception can include some field with needed state, and be handled by `ConversationHandler` which will set state and throw an exception to the dispatcher.

> Using a method like bot.dispatcher.stop_propagation() would be an option, but it would be a bit strange, especially since there is no real reason for Bot to have a reference to Dispatcher. What do you think?

Yes, I've just mixed up `bot` with `updater`. My bad.


Btw, this is #666 issue 😈

**Comment by s-chizhik** [comment] 2017-06-14 09:27
I've send you a PR with proposed changes, so we can talk more specifically :)

**Comment by s-chizhik** [comment] 2017-06-18 08:20
@jh0ker, any updates?

**Closed** 2017-07-29 17:15 UTC
Labels: duplicate, enhancement
