### ISSUE TITLE
Bug. Function disable_web_page_preview doesn't work.

### ISSUE THREAD

**Issue by evtuhovaleksander** [python-telegram-bot/python-telegram-bot#596] opened 2017-05-10 11:27 UTC
### Steps to reproduce
1.use method send_message() with some text and argument disable_web_page_preview set to True
for example
bot.send_message(text='https://www.google.ru/', chat_id=update.message.chat_id,disable_web_page_preview=True)

### Expected behaviour
Tell us what should happen
The message that' has come to telegram must not have a link preview part 

### Actual behaviour
Tell us what happens instead
The message still has a link preview part

### Configuration
**Operating System:**
doesn't matter
bug was found on ubuntu 16.04/16.10, Heroku, OS X 10.12 Sierra

**Version of Python, python-telegram-bot & dependencies:**
python 3.5.2

python-telegram-bot==5.3.0
Django==1.10.6
gunicorn==19.6.0
dj-database-url==0.4.1
psycopg2==2.6.2
whitenoise==3.2
urllib3==1.20
requests==2.10.0
pyTelegramBotAPI==2.1.7

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Eldinnie** [comment] 2017-05-10 14:14
I can not reproduce this...
![image](https://cloud.githubusercontent.com/assets/1409173/25903057/a665c8e4-359b-11e7-898d-b5432af23dbf.png)
![image](https://cloud.githubusercontent.com/assets/1409173/25903067/ae1401c8-359b-11e7-8b2b-ddb0b09d1bb6.png)

**Comment by bomjacob** [comment] 2017-05-12 14:19
Unable to reproduce too, closing issue. Feel free to open if you have additional input.

**Closed by bomjacob** 2017-05-12 14:19 UTC
