### ISSUE TITLE
Bot is responding to commands for other bots in group chats when privacy option is turned off

### ISSUE THREAD

**Issue by blueset** [python-telegram-bot/python-telegram-bot#319] opened 2016-06-01 10:35 UTC
### Steps to reproduce
1. Get a bot, turn off privacy option in `@botfather`, and drag it in a group with other bots (which should respond to `/start` command in a group).
2. Set up the bot with the following code:

``` python
import telegram, telegram.ext
tb = telegram.ext.Updater("TOKEN")
def a(bot, update):
    bot.sendMessage(update.message.chat_id, "responding to /start cmd")

tb.dispatcher.add_handler(telegram.ext.CommandHandler("start", b))
tb.start_polling()
```
1. Send command `/start@some_other_bot` to the group, and your bot will respond to it.
2. Send command `/start` to the group and your bot (and in fact many other bots) will respond to it too.
### Expected behaviour

Bot should not respond to cmds not pointing to it, and better give an option not to respond to cmd with no target in a group.
### Configuration

**Operating System:**
Mac OS X El Capitan

**Version of Python:**

`$ python3 -V`

`Python 3.5.1`

**Version of python-telegram-bot:**

`$ python3 -c 'import telegram; print(telegram.__version__)'`

`4.1.1`
### Logs

Insert logs here (if necessary)
### Where the issue happens

``` python
update.message.text[1:].split(' ')[0].split('@')[0] == self.command
```

on line 45 of `telegram/ext/commandhandler.py`
It is not checking for the target of command issued by user.
### Suggested changes
1. [ ] Check for commands with `@` for whether it's pointed to the bot.
2. [ ] Add a parameter to `CommandHandler`: toggle whether if the bot should respond to simple commands (command without `@name_of_the_bot`) in a group, and default it to True. (for backward compatibility, and behaviour consistancy)

**Comment by Eldinnie** [comment] 2016-06-01 10:43
What I find weird is that telegram pushes this message to the bot. It does not with other command maybe /start and /help can't be directed to a specific bot?

**Comment by blueset** [comment] 2016-06-05 12:03
@Eldinnie 

Similar test has been conducted with:
* Command `/join`
* Bot `@mau_mau_bot`

and it can be reproduced.

**Comment by Eldinnie** [comment] 2016-06-06 16:07
From bot faq

What messages will my bot get?
...
General commands from users (e.g. /start) if your bot was the last bot that sent a message to the group.

**Comment by blueset** [comment] 2016-06-15 18:24
@TiagoDanin 
I understand that the bot will get *all messages* when privacy mode is turned off. However, we should enable `CommandHandler` to filter out commands we don't want, in order to run it smoothly, as there is still cases that the bot need to get all messages in a group, while ignoring commands for other bots.

**Comment by jh0ker** [comment] 2016-06-16 16:08
I agree that this behavior is unexpected. However I met some problems implementing a solution, and I'd like some opinion.

My plan was to run `bot.getMe()` in `Dispatcher.__init__`, save the username and then check for that username in `CommandHandler.check_update`. That method is inherited from the `Handler` class and decides if an update should be handled by that particular handler instance.

The problem: The `CommandHandler` class has no local reference to the `Dispatcher` and therefore no way to access the username. Creating this reference would require one of two things:

- Change the API of the `Handler` class to pass it as an (optional) argument to `check_update`, or
- In `Dispatcher.add_handler` check `isinstance(handler, CommandHandler)` and create a local reference there

I don't really like either of those. Do you think it's worth it?

**Comment by Eldinnie** [comment] 2016-06-21 09:34
Doing this means breaking functionality as offered by Telegram.
As far as I can see the bot receives messages only if it applies to above rules. Why do you feel the module should filter them out further? It might break functionality for bots.

> Commands from users meant for your bot (e.g. /start@YourBot).
> General commands from users (e.g. /start) if your bot was the last bot that sent a message to the group.
This makes it pretty clear why you get the updates. And I don't see why you should filter them out.

**Comment by blueset** [comment] 2016-06-21 11:32
@Eldinnie The cases introduced in the documentation is ONLY for the case when privacy setting is turned ON. However, clearly stated in the title, in this issue title we're discussing about the case when privacy setting is turned OFF, which the bot will get ALL messages from the group, with no restriction. So when a command is explicitly meant for another bot, the message should be filtered out in both privacy setting modes, and it's not filtered out for now. This hence is a bug.

**Comment by franciscod** [comment] 2016-08-11 09:49
@jh0ker what if we bailed out early in`handle_update`? Is that a good compromise?

**Comment by bomjacob** [comment] 2016-09-26 07:12
What if we added a kwarg `strict=False` to `CommandHandler`?
If `True` it would allow only commands with its `@bot.name`.

**Comment by Centzilius** [comment] 2016-10-04 20:40
This seems to only affect supergroups (at least for me). Maybe it should be reported to the telegram devs instead.

**Comment by Eldinnie** [comment] 2017-02-05 01:33
@jh0ker since the bot is a parameter for an update nowadays. Wouldn't it be possible to check the bot's getme against commands botname to verify the bot should respond to it?
It's also a bug from telegram, since I just had an incident with someone elses bot (written in php) with the same problem.

**Comment by jh0ker** [comment] 2017-02-05 08:18
@Eldinnie Oh nice catch! I think it's even already being cached in the Bot class already.

**Comment by Eldinnie** [comment] 2017-02-05 12:55
confirmed that bot.username in the callback method for a commandHandler returns the bot's username. I think this can be solved pretty easy. Will try to find some time later tonight

**Comment by Eldinnie** [comment] 2017-02-05 21:17
@jh0ker can you see if this fixes the problem? The tests fail, but on other tests and I added tests to check if it shows expected behaviour to tests\test_updater.py

**Comment by Eldinnie** [comment] 2017-05-15 18:33
this is resolved IIRC, so maybe close the issue :D

**Closed** 2017-05-19 23:14 UTC
Labels: bug
