### ISSUE TITLE
Send message to private channels

### ISSUE THREAD

**Issue by hmdhasani** [python-telegram-bot/python-telegram-bot#538] opened 2017-03-02 13:15 UTC
I can send message to a public channel by chat_id="@channel public id"
How can I send a message to a private channel?

**Comment by jh0ker** [comment] 2017-03-15 12:02
There are probably other ways, but I'm using [Plus Messenger](https://play.google.com/store/apps/details?id=org.telegram.plus) and it shows the ID for users, groups and private channels in their profile. Maybe that helps you?

**Comment by vharcan** [comment] 2017-03-17 00:22
Log into Telegram via web: https://web.telegram.org
Find your channel and copy the URL. You should have something like this: https://web.telegram.org/#/im?p=c**NUMBER**_number
The numbers between "c" and "_" are the ID of your private channel.

Now tell your bot to send the messages to chat_id=**-100**NUMBER

**Comment by hmdhasani** [comment] 2017-03-17 13:37
I will check that

**Comment by jh0ker** [comment] 2017-04-01 10:50
I'll close this issue - if the problem is not resolved, feel free to re-open

**Closed by jh0ker** 2017-04-01 10:50 UTC
Labels: question

**Comment by hojjatazimi** [comment] 2017-08-19 10:47
thanks a lot

**Comment by soser1488** [comment] 2017-12-03 00:10
trying chat_id = chatid 
where chatid = '-13590203204002368949467783325'
don't working, help plz

**Comment by jh0ker** [comment] 2017-12-03 00:13
@soser1488 
Hi,

This is not an issue with the library's code, but a usage question. Feel free to ask it in our [Telegram group](https://t.me/pythontelegrambotgroup).
In case you are unable to join our group due to Telegram restrictions, you can use our [IRC channel](https://webchat.freenode.net/?channels=##python-telegram-bot) to participate in the group.
