### ISSUE TITLE
[QUESTION] CallbackQueryHandler doesn't work correctly in basic examples

### ISSUE THREAD

**Issue by vkurilin** [python-telegram-bot/python-telegram-bot#3722] opened 2023-05-28 11:53 UTC
### Steps to Reproduce

1. Import and set up the python-telegram-bot library.
2. Run the nestedconversationbot.py, inlinekeyboard.py, or inlinekeyboard2.py examples.
3. Issue the initial/start command. The inline menu should appear.
4. Click any button within the inline menu.

### Expected behaviour

Clicking a button in the inline menu should further the dialogue according to the script's logic, responding to the user input.

### Actual behaviour

Clicking any button within the inline menu does not result in any further action or dialogue progression. The dialogue flow is halted.

### Operating System

MacOS 13.4 (22F66)

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 20.3 (0.2.5-23-g173e120)
Bot API 6.7
Python 3.11.1 (main, Dec 21 2022, 12:09:26) [Clang 14.0.0 (clang-1400.0.29.202)]
```

### Additional Context

I've tried implementing the CallbackQueryHandler both with and without a pattern, but the handler still does not get called. 
Other handlers (e.g.the MessageHandler and CommandHandler) function as expected in these scripts

**Comment by Poolitzer** [comment] 2023-05-28 12:34
@vkurilin Hey, the issue is that you specifically set which update types your bot should receive sometime ago and our example don&#x27;t (yet) set which update types they need. You need to specifically set this in application.run_polling, to either Update.ALL or the types required, callbackqueries and messages.

**Comment by vkurilin** [comment] 2023-05-28 12:44
Thank you so much! 

Indeed, it worked in the following сode:

```python
application.run_polling(allowed_updates=Update.ALL_TYPES)
```

Do you think it makes sense to make a PR adding allowed_updates to the basic examples to make them more beginner-friendly for those trying the bot?

**Comment by clot27** [comment] 2023-05-28 12:58
@vkurilin Sure, you can open a PR regarding that if you want to :)

**Comment by Bibo-Joshi** [comment] 2023-05-31 20:09
Closing in favor of #3726. @vkurilin if you would like to work on that issue, please leave a short comment so that we can assign you.

**Closed by Bibo-Joshi** 2023-05-31 20:09 UTC
Labels: question
