### ISSUE TITLE
[BUG] APScheduler version issue

### ISSUE THREAD

**Issue by aliencaocao** [python-telegram-bot/python-telegram-bot#3259] opened 2022-09-27 15:17 UTC
### Steps to Reproduce

1. pip install -U python-telegram-bot
2. pip install -U ASPSchedular

### Expected behaviour

PIP does not show version conflict for APScheduler

### Actual behaviour

PIP shows warning that `python-telegram-bot 13.14 requires APScheduler==3.6.3, but you have apscheduler 3.9.1 which is incompatible.`
However by the readme document and requirements.txt, 3.9.1 is compatible.
Tried uninstalling and reinstalling python-telegram-bot, same issue (it just forces me to install APSCheduler 3.6.3.

### Operating System

Windows 10 64bit

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.14
Bot API 6.2
certifi2022.09.24
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
```

### Relevant log output

```python
python-telegram-bot 13.14 requires APScheduler==3.6.3, but you have apscheduler 3.9.1 which is incompatible.
```

**Comment by Poolitzer** [comment] 2022-09-28 07:47
Hey there.

You are correct, pip shows you a warning about version conflict. You are incorrect though in stating that pip forces you to install APScheduler 3.6.3. If you do
```
pip install -U python-telegram-bot
pip install -U APScheduler
pip show apscheduler
```
You will see that apscheduler will be 3.9.1. You are free to use the newer version, it is unlikely that it breaks anything we implement in PTB. However, since V13 is depreciated and in Bot API maintenance release mode only, we are hesitant in changing anything else.

You are more than welcome to use V20 instead where we reworked our dependency policy.

**Comment by Bibo-Joshi** [comment] 2022-09-28 08:00
Closing as duplicate of #2929.

**Closed by Bibo-Joshi** 2022-09-28 08:00 UTC
Labels: bug :bug:

**Comment by aliencaocao** [comment] 2022-09-28 08:15
What i meant was if i install aspscheduler first then install telegram bot, it will force downgrade my aspscheduler and that is bad because other modules i have breaks on older aspscheduler.

**Comment by Poolitzer** [comment] 2022-09-28 08:16
@aliencaocao If you have them in a requirements.txt file, adding APScheduler with a non breaking version after python-telegram-bot should still work.

**Comment by aliencaocao** [comment] 2022-09-28 08:57
Ok.
Can I also confirm whether the tornado package have to be pinned to v6.1, or is that also can be upgraded like aspscheduler?

**Comment by Bibo-Joshi** [comment] 2022-09-28 08:59
See #3145
