### ISSUE TITLE
Exception on 'bot.get_chat_administrators' in private chat

### ISSUE THREAD

**Issue by Endogen** [python-telegram-bot/python-telegram-bot#1188] opened 2018-08-12 19:28 UTC
### Steps to reproduce
1. Be in a private hat

2. Execute `admin_list = bot.get_chat_administrators(update.message.chat_id)`

3. Exception BadRequest: There is no administrators in the private chat

### Expected behaviour
I would expect to get back None or an empty list

### Actual behaviour
Exception raised

### Configuration
**Operating System:**
macOS 10.13.6

**Version of Python, python-telegram-bot & dependencies:**
python-telegram-bot 10.1.0
certifi 2018.04.16
future 0.16.0
Python 3.7.0 (default, Jun 29 2018, 20:13:13)  [Clang 9.1.0 (clang-902.0.39.2)]

Of course i could just catch the exception but since i want to use this bot in a private chat and also in a supergroup, i would expect PTB to see this as a valid use-case and since there are no admins in a private chat, i feel like None or an empty list would be more appropriate. Why the need for an exception?

**Comment by jsmnbom** [comment] 2018-08-12 19:31
The exception is coming from telegram (since they send back a BadRequest error).
I personally think catching it in the get_chat_administrators and returning an empty list seems like a good idea.

**Comment by Endogen** [comment] 2018-08-12 19:36
Actually, i would vote for `None`. Since you then can distinguish between a supergroup and a private chat. Because it could be that there are no admins in a supergroup(? not sure about that) and that would then be an empty list.

For a private chat it would be `None` and thus it's clear in which context you are.

**Comment by jsmnbom** [comment] 2018-08-12 19:38
If you wanna know what context you're in just check the chat.type.
Returning a list means you can do stuff like:

```python
for admin in bot.get_chat_administrators(update.message.chat_id):
    # do smth with admin
```

without getting errors.

**Comment by Endogen** [comment] 2018-08-12 19:39
Makes sense

**Comment by tsnoam** [comment] 2018-08-12 19:45
@jsmnbom Personally I think that parsing literals and guessing what exactly is the problem is an endless pit.
Raising an exception is the proper way imho.
GitHub:
💬 New comment on python-telegram-bot#1188 Exception on 'bot.get_chat_administrators' in private chat
by @Endogen

Makes sense

Reply to this message to post a comment on GitHub.

Lets put it like this: I prefer to maintain the original semantics (i.e. telegram's). Hiding telegram's semantics behind special behavior will make the code more confusing and harder to maintain.

**Comment by Endogen** [comment] 2018-08-12 20:11
> Hiding telegram's semantics behind special behavior will make the code more confusing and harder to maintain

That's for sure true. From a user perspective i feel like it's not the expected behavior but makes sense from dev point of view.

I have nothing agains letting it be like it is. In my case i use `if chat.type == chat.PRIVATE:` to check if it's a private conversation and then i don't execute `get_chat_administrators()`

**Comment by tsnoam** [comment] 2018-08-12 20:14
@Endogen Maybe we should suggest this snippet in the docstring.
@EchteEldin  what do think?

**Comment by Endogen** [comment] 2018-08-12 20:16
Good idea IMO 👍

**Comment by Eldinnie** [comment] 2018-08-12 20:18
@tsnoam I don;t know wat snippet, but to me it makes no sense to check for admins in a PM. I would make sure methods that do that are not used with PM's. Either with a check in chat.type or a filter. Leaving the Error as it is, is in line with the rest of the library (merely relaying the errors TG sends us), so I prefer it to stay that way.

**Comment by jh0ker** [comment] 2018-08-12 20:38
I agree with @tsnoam, also quoting the [Zen of Python](https://www.python.org/dev/peps/pep-0020/):

> Errors should never pass silently.
> Unless explicitly silenced.

**Comment by jsmnbom** [comment] 2018-08-12 20:40
Closing issue, since general consensus seems to be wontfix.

**Closed by jsmnbom** 2018-08-12 20:40 UTC
Labels: enhancement

**Comment by tsnoam** [comment] 2018-08-12 20:44
Just a little clarification from the developers discussion:
1. The documentation of get_chat_administrators is already very thorough.
2. Anything else in the behavior is undocumented by telegram themselves and it isn't in our place to document such behavior.
3. As stated above, we find the value in reflecting the real error and not silently ignore it.

**Comment by enea1982** [comment] 2018-09-11 14:28
hello you can give me help for your bot gives me a mistake
from telegram import KeyboardButton, ReplyKeyboardMarkup, ReplyKeyboardRemove, ParseMode
from: can't read /var/mail/telegram

**Comment by enea1982** [comment] 2018-09-11 14:29
the bot and kraken bot
