### ISSUE TITLE
using switch_inline_query i made to pop up the contacts and by selecting it should send game via bot but it is normal private user works in Gamee bot

### ISSUE THREAD

**Issue by Misaac77** [python-telegram-bot/python-telegram-bot#857] opened 2017-10-04 12:13 UTC
### Steps to reproduce
1.

2.

3.

### Expected behaviour
Tell us what should happen
responce to bot when user is selected through switch_inline_query 
### Actual behaviour
Tell us what happens instead
it is taking me to user account and stoped 

### Configuration
**Operating System:**
ubuntu

**Version of Python, python-telegram-bot & dependencies:**
3.6

``$ python -m telegram``

### Logs
Insert logs here (if necessary)

**Comment by Eldinnie** [comment] 2017-10-04 13:10
Please fill in out template to explain what the problem is.

**Comment by Eldinnie** [comment] 2017-10-10 08:14
Closing this due to a lack of respons

**Closed by Eldinnie** 2017-10-10 08:14 UTC
