### ISSUE TITLE
[BUG] ImportError: cannot import name 'Type': python-telegram-bot

### ISSUE THREAD

**Issue by stormstricker** [python-telegram-bot/python-telegram-bot#1670] opened 2019-12-22 18:24 UTC
I'm trying to run this simple example:

```
import logging

from telegram.ext import Updater, CommandHandler, MessageHandler, Filters

# Enable logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    level=logging.INFO)

logger = logging.getLogger(__name__)


# Define a few command handlers. These usually take the two arguments update and
# context. Error handlers also receive the raised TelegramError object in error.
def start(update, context):
    """Send a message when the command /start is issued."""
    update.message.reply_text('Hi!')


def help(update, context):
    """Send a message when the command /help is issued."""
    update.message.reply_text('Help!')


def echo(update, context):
    """Echo the user message."""
    update.message.reply_text(update.message.text)


def error(update, context):
    """Log Errors caused by Updates."""
    logger.warning('Update "%s" caused error "%s"', update, context.error)


def main():
    """Start the bot."""
    # Create the Updater and pass it your bot's token.
    # Make sure to set use_context=True to use the new context based callbacks
    # Post version 12 this will no longer be necessary
    updater = Updater(mytokenwashere, use_context=True)

    # Get the dispatcher to register handlers
    dp = updater.dispatcher

    # on different commands - answer in Telegram
    dp.add_handler(CommandHandler("start", start))
    dp.add_handler(CommandHandler("help", help))

    # on noncommand i.e message - echo the message on Telegram
    dp.add_handler(MessageHandler(Filters.text, echo))

    # log all errors
    dp.add_error_handler(error)

    # Start the Bot
    updater.start_polling()

    # Run the bot until you press Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT. This should be used most of the time, since
    # start_polling() is non-blocking and will stop the bot gracefully.
    updater.idle()


if __name__ == '__main__':
    main()
```

But I get the error:

```
ImportError: cannot import name 'Type'
```

on line

```
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
```

Before I've run

```
$ pip install python-telegram-bot --upgrade
```
once I had this error I tried

```
pip uninstall python-telegram-bot
```
and then

```
$ git clone https://github.com/python-telegram-bot/python-telegram-bot --recursive
$ cd python-telegram-bot
$ python setup.py install
```
but the error continued. I'm at the end of my ropes here.

**Comment by Eldinnie** [comment] 2019-12-22 19:18
Please post a full traceback.

**Comment by stormstricker** [comment] 2019-12-22 20:57
```
C:\Python\Python35-32\python.exe "D:/.../TelegramBot.py"
Traceback (most recent call last):
  File "D:/.../TelegramBot.py", line 3, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
  File "C:\Python\Python35-32\lib\site-packages\python_telegram_bot-12.2.0-py3.5.egg\telegram\ext\__init__.py", line 28, in <module>
    from .updater import Updater
  File "C:\Python\Python35-32\lib\site-packages\python_telegram_bot-12.2.0-py3.5.egg\telegram\ext\updater.py", line 33, in <module>
    from telegram.utils.webhookhandler import (WebhookServer, WebhookAppClass)
  File "C:\Python\Python35-32\lib\site-packages\python_telegram_bot-12.2.0-py3.5.egg\telegram\utils\webhookhandler.py", line 27, in <module>
    from tornado.httpserver import HTTPServer
  File "C:\Python\Python35-32\lib\site-packages\tornado-6.0.3-py3.5-win32.egg\tornado\httpserver.py", line 31, in <module>
    from tornado.escape import native_str
  File "C:\Python\Python35-32\lib\site-packages\tornado-6.0.3-py3.5-win32.egg\tornado\escape.py", line 27, in <module>
    from tornado.util import unicode_type
  File "C:\Python\Python35-32\lib\site-packages\tornado-6.0.3-py3.5-win32.egg\tornado\util.py", line 21, in <module>
    from typing import (
ImportError: cannot import name 'Type'

Process finished with exit code 1

```

**Comment by Bibo-Joshi** [comment] 2019-12-22 21:14
Hi @stormstricker. As you can tell from the traceback, the issue is with tornado. See [#2623](https://github.com/tornadoweb/tornado/issues/2623): Tornado 6 is compatible with Python >= 3.5.2.
Please either use a newer Python version or downgrade Tornado to 5.1.1.
I'll be closing this because the issue is not with ptb.

**Closed by Bibo-Joshi** 2019-12-22 21:14 UTC
Labels: bug :bug:
