### ISSUE TITLE
exe not working (PyInstaller, windows)

### ISSUE THREAD

**Issue by fabioparodi** [python-telegram-bot/python-telegram-bot#2697] opened 2021-10-04 13:22 UTC
### Steps to Reproduce

1. create a minimal test.py with the content below
```
import telegram.ext
updater = telegram.ext.Updater(token="2234234492:AAGAplU3AIdH_zvTXh1D30sdfgrerwfTz-0")
updater.dispatcher.job_queue.run_once(lambda context: print("hello world"), 0)
updater.start_polling()
updater.idle()
```
2. run the command:
`pyinstaller.exe --noconfirm test.py`
it will create a file test.exe in directory dist\test
3. run exe:
`dist\test\test.exe`

### Expected behaviour

print `hello world`
then fail because the token is invalid

### Actual behaviour

fail with message:
`pkg_resources.DistributionNotFound: The 'pytz' distribution was not found and is required by the application`

### Operating System

windows 10

### Version of Python, python-telegram-bot & dependencies

```shell
python-telegram-bot 13.7
Bot API 5.3
certifi 2021.05.30
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:05:41) [MSC v.1929 32 bit (Intel)]
```

### Relevant log output

```python
66 INFO: PyInstaller: 4.5.1
66 INFO: Python: 3.9.7
77 INFO: Platform: Windows-10-10.0.19043-SP0
78 INFO: wrote C:\Users\FabioParodi\Documents\RDI_WATCHER\telegram\test.spec
80 INFO: UPX is not available.
88 INFO: Extending PYTHONPATH with paths
['C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\telegram',
 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\telegram']
306 INFO: checking Analysis
306 INFO: Building Analysis because Analysis-00.toc is non existent
306 INFO: Initializing module dependency graph...
309 INFO: Caching module graph hooks...
321 INFO: Analyzing base_library.zip ...
2651 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2652 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib'
3281 INFO: Processing pre-find module path hook site from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
3283 INFO: site: retargeting to fake-dir 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\fake-modules'
6628 INFO: Caching module dependency graph...
6853 INFO: running Analysis Analysis-00.toc
6858 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\FabioParodi\Documents\RDI_WATCHER\Python32\python.exe
6885 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of C:\Users\FabioParodi\Documents\RDI_WATCHER\Python32\python39.dll
6913 INFO: Analyzing C:\Users\FabioParodi\Documents\RDI_WATCHER\telegram\test.py
6916 INFO: Processing module hooks...
6917 INFO: Loading module hook 'hook-apscheduler.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
7245 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
7251 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
7254 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
7256 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
7352 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
7356 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
7359 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
7362 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
7746 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
8071 WARNING: Hidden import "pkg_resources.py2_warn" not found!
8072 WARNING: Hidden import "pkg_resources.markers" not found!
8077 INFO: Loading module hook 'hook-pytz.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
8234 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
8236 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
8391 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
8393 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
8395 INFO: Loading module hook 'hook-pythoncom.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8658 INFO: Loading module hook 'hook-pywintypes.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8911 INFO: Loading module hook 'hook-win32com.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
9168 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
9172 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks'...
9244 INFO: Looking for ctypes DLLs
9263 INFO: Analyzing run-time hooks ...
9268 INFO: Including run-time hook 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
9273 INFO: Including run-time hook 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
9276 INFO: Including run-time hook 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
9279 INFO: Including run-time hook 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
9283 INFO: Including run-time hook 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32api.py'
9283 INFO: Including run-time hook 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win32comgenpy.py'
9286 INFO: Including run-time hook 'C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_certifi.py'
9294 INFO: Looking for dynamic libraries
9595 INFO: Looking for eggs
9595 INFO: Using Python library C:\Users\FabioParodi\Documents\RDI_WATCHER\Python32\python39.dll
9597 INFO: Found binding redirects:
[]
9614 INFO: Warnings written to C:\Users\FabioParodi\Documents\RDI_WATCHER\telegram\build\test\warn-test.txt
9704 INFO: Graph cross-reference written to C:\Users\FabioParodi\Documents\RDI_WATCHER\telegram\build\test\xref-test.html
9746 INFO: checking PYZ
9746 INFO: Building PYZ because PYZ-00.toc is non existent
9747 INFO: Building PYZ (ZlibArchive) C:\Users\FabioParodi\Documents\RDI_WATCHER\telegram\build\test\PYZ-00.pyz
10618 INFO: Building PYZ (ZlibArchive) C:\Users\FabioParodi\Documents\RDI_WATCHER\telegram\build\test\PYZ-00.pyz completed successfully.
10653 INFO: checking PKG
10653 INFO: Building PKG because PKG-00.toc is non existent
10654 INFO: Building PKG (CArchive) PKG-00.pkg
10692 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
10694 INFO: Bootloader C:\Users\FabioParodi\Documents\RDI_WATCHER\Python32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
10695 INFO: checking EXE
10696 INFO: Building EXE because EXE-00.toc is non existent
10697 INFO: Building EXE from EXE-00.toc
10699 INFO: Copying icons from ['C:\\Users\\FabioParodi\\Documents\\RDI_WATCHER\\Python32\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
10703 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
10703 INFO: Writing RT_ICON 1 resource with 3752 bytes
10703 INFO: Writing RT_ICON 2 resource with 2216 bytes
10705 INFO: Writing RT_ICON 3 resource with 1384 bytes
10705 INFO: Writing RT_ICON 4 resource with 37019 bytes
10705 INFO: Writing RT_ICON 5 resource with 9640 bytes
10706 INFO: Writing RT_ICON 6 resource with 4264 bytes
10706 INFO: Writing RT_ICON 7 resource with 1128 bytes
10709 INFO: Appending archive to EXE C:\Users\FabioParodi\Documents\RDI_WATCHER\telegram\build\test\test.exe
11834 INFO: Building EXE from EXE-00.toc completed successfully.
11840 INFO: checking COLLECT
11840 INFO: Building COLLECT because COLLECT-00.toc is non existent
11841 INFO: Building COLLECT COLLECT-00.toc
12823 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

### Additional Context

I am not really sure the bug is in telegram-bot; however, I have several othe projects with PyInstaller running just fine.
The error message changes at random:
`pkg_resources.DistributionNotFound: The 'XXX' distribution was not found and is required by the application`
with XXX in: pytz, tzlocal, six, setuptools, ...
I have tried to add the missing module to the hiddenimports list, no success.
I am willing to help ...

**Comment by fabioparodi** [comment] 2021-10-04 13:23
I did try python 64 bit, same result

**Comment by Bibo-Joshi** [comment] 2021-10-04 14:15
Hi. We can't give support for pyinstaller here. So closing as more-or-less duplicate of #2499.

**Closed by Bibo-Joshi** 2021-10-04 14:15 UTC
Labels: bug :bug:

**Comment by fabioparodi** [comment] 2021-10-05 08:28
Solved by adding the following arguments to the PyInstaller invocation script:
`--recursive-copy-metadata apscheduler`
